(function( spot_ns, $, undefined ) {
  "use strict";

  /* check_viable returns a viable potion or null
   * idx = base index
   * hash = find dups
   * X = 1st ingredient
   * Y = 2nd ingredient
   */
  function check_viable( idx, hash, X, Y )
  {
    var effect = [];
    var viable = false;
    var pos = idx.p.x;

    // all ingredients have 4 effects
    for(var a=0; a<4; ++a )
    {
      var ai = X.e[a].x;

      for(var b=0; b<4; ++b )
      {
        if( ai == Y.e[b].x )
        {
          viable = true;
          effect.push(ai);
          idx.eff.pot[ai].push( pos );
        }
      }
    }

    if( ! viable ) return null;

    idx.pot.num++;
    var pot = {
      x: pos,
      i: (X.idx<Y.idx)
        ?[ X.idx, Y.idx ]
        :[ Y.idx, X.idx ],
      e: effect.sort( function(a,b) { return( a-b ); } )
    };

    idx.pot.lab.push( pot );
    idx.pot.ni[2].push( pos );
    idx.pot.ne[effect.length].push( pos );
    idx.ing.pot[X.idx].push( pos );
    idx.ing.pot[Y.idx].push( pos );

    return pot;
  }

  function potHash( idx, hash, X, Y )
  {
    var XY = X.nam + ":" + Y.nam
    if( XY in hash ) return;

    hash[ XY ] = check_viable( idx, hash, X, Y );
    return;
  }


  function buildPotions(idx)
  {
    var tmp = {};
    var A, B, C;
    var len = idx.ing.lab.length;

    for( var a=0; a<len-2; a++ )
    {
      A = idx.ing.lab[a];
      for( var b=a+1; b<len-1; b++ )
      {
        B = idx.ing.lab[b];
        potHash( idx, tmp, A, B );

        for( var c=b+1; c<len; c++ )
        {
          C = idx.ing.lab[c];
          potHash( idx, tmp, A, C );
          potHash( idx, tmp, B, C );
        }
      }
    }
  }

}( window.spot_ns = window.spot_ns || {}, jQuery ));

$(document).ready(function () {

  var index = spot_ns.index;

  index.p = {};
  index.p.z = 0;
  index.p.l = [];
  index.p.i = [ null, null, [], [] ];
  index.p.e = [ null, [], [], [], [], [], [], [] ];

  console.info( 'potion building' );
  spot_ns.buildPotions(index);

  $("#fullJSON").text(
      "// autogenerated content -- DO NOT MODIFY\n"
    + "(function( spot_ns, \$, undefined ) {\n"
    + "spot_ns.index = \n"
    + JSON.stringify( index, null, ' ')
    + ";\n}( window.spot_ns = window.spot_ns || {}, jQuery ));\n" );
});
// vim: set ts=2 sw=2 et:
