/* autogenerated content -- DO NOT MODIFY
 * to change this data you must:
 * 1. edit js/parser.js
 * 2. load parser.html
 * 3. paste the content into js/idx.js
 */

function getIdx() { return({
 "ingL": [
  {
   "idx": 0,
   "nam": "Abecean Longfin",
   "val": "15",
   "wgt": "0.5",
   "plt": "Common",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Weakness to Frost",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Sneak",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Weakness to Poison",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Restoration",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected by catching Abacean Longfin fish."
  },
  {
   "idx": 1,
   "nam": "Ancestor Moth Wing",
   "val": "2",
   "wgt": "0.1",
   "plt": "None",
   "dlc": "DG",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Conjuration",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Magicka Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Enchanting",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected by catching Ancestor Moths."
  },
  {
   "idx": 2,
   "nam": "Bear Claws",
   "val": "2",
   "wgt": "0.1",
   "plt": "None (Uncommon)",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Stamina",
     "val": 1,
     "mag": "0.8",
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Health",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify One-handed",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Magicka Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Collected from various types of dead Bears."
  },
  {
   "idx": 3,
   "nam": "Bee",
   "val": "3",
   "wgt": "0.1",
   "plt": "Common",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Ravage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Regenerate Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Weakness to Shock",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Collected from beehives and by catching Bees."
  },
  {
   "idx": 4,
   "nam": "Beehive Husk",
   "val": "5",
   "wgt": "1",
   "plt": "None (Common)",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Resist Poison",
     "val": 1,
     "mag": "0.5",
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Light Armor",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Sneak",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Destruction",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from beehives."
  },
  {
   "idx": 5,
   "nam": "Bleeding Crown",
   "val": "10",
   "wgt": "0.3",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Weakness to Fire",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Block",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Weakness to Poison",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Resist Magic",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from Bleeding Crown, a mushroom found in various caves."
  },
  {
   "idx": 6,
   "nam": "Blisterwort",
   "val": "12",
   "wgt": "0.2",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Frenzy",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Restore Health",
     "val": 1,
     "mag": "0.6",
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Smithing",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from Blisterwort mushrooms found in various caves."
  },
  {
   "idx": 7,
   "nam": "Blue Butterfly Wing",
   "val": "2",
   "wgt": "0.1",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Conjuration",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Magicka Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Enchanting",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected by catching Blue Butterflies. Often found during daylight hours near flowering plants."
  },
  {
   "idx": 8,
   "nam": "Blue Dartwing",
   "val": "1",
   "wgt": "0.1",
   "plt": "None (Uncommon)",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Resist Shock",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Pickpocket",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Restore Health",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fear",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Collected by catching Dragonflies found near rivers and streams below the snow line."
  },
  {
   "idx": 9,
   "nam": "Blue Mountain Flower",
   "val": "2",
   "wgt": "0.1",
   "plt": "Common",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Health",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Conjuration",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Health",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Magicka Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Harvested from the blue variety of Mountain Flower, found throughout Skyrim."
  },
  {
   "idx": 10,
   "nam": "Bone Meal",
   "val": "5",
   "wgt": "0.5",
   "plt": "Common",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Resist Fire",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Conjuration",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Ravage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Collected from undead such as skeletons, and Draugr."
  },
  {
   "idx": 11,
   "nam": "Briar Heart",
   "val": "20",
   "wgt": "0.5",
   "plt": "Rare",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Block",
     "val": 1,
     "mag": "0.5",
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Paralysis",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from Forsworn Briarhearts."
  },
  {
   "idx": 12,
   "nam": "Butterfly Wing",
   "val": "3",
   "wgt": "0.1",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Health",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Barter",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Lingering Damage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Damage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Collected from catching Monarch Butterflies. Often found during daylight hours near flowering plants."
  },
  {
   "idx": 13,
   "nam": "Canis Root",
   "val": "5",
   "wgt": "0.1",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify One-handed",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Marksman",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Paralysis",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Harvested from Canis Root, found in The Rift and Hjaalmarch."
  },
  {
   "idx": 14,
   "nam": "Charred Skeever Hide",
   "val": "1",
   "wgt": "0.5",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Cure Disease",
     "val": "0.36",
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Resist Poison",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Restore Health",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Food, collected from dead Skeevers found on roasting spits."
  },
  {
   "idx": 15,
   "nam": "Chaurus Eggs",
   "val": "10",
   "wgt": "0.2",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Weakness to Poison",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Invisibility",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from Chaurus Egg Sacs, found in Falmer caves."
  },
  {
   "idx": 16,
   "nam": "Chaurus Hunter Antennae",
   "val": "2",
   "wgt": "0.1",
   "plt": "None",
   "dlc": "DG",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Conjuration",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Magicka Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Enchanting",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from dead Chaurus Hunters and Chaurus Hunter Fledglings."
  },
  {
   "idx": 17,
   "nam": "Chicken's Egg",
   "val": "2",
   "wgt": "0.5",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Resist Magic",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Magicka Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Waterbreathing",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Lingering Damage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Food, harvested from Chicken nests in various farms."
  },
  {
   "idx": 18,
   "nam": "Creep Cluster",
   "val": "1",
   "wgt": "0.2",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Stamina Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Carry Weight",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Weakness to Magic",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Harvested from Creep Cluster, found in the volcanic tundra of Eastmarch."
  },
  {
   "idx": 19,
   "nam": "Crimson Nirnroot",
   "val": "10",
   "wgt": "0.2",
   "plt": "None",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Health",
     "val": 1,
     "mag": "3",
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Damage Stamina",
     "val": 1,
     "mag": "3",
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Invisibility",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Resist Magic",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from Crimson Nirnroot, found in Blackreach, needed for the quest A Return To Your Roots."
  },
  {
   "idx": 20,
   "nam": "Cyrodilic Spadetail",
   "val": "15",
   "wgt": "0.25",
   "plt": "Common",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Restoration",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fear",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Ravage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Collected by catching Cyrodilic Spadetail fish."
  },
  {
   "idx": 21,
   "nam": "Daedra Heart",
   "val": "250",
   "wgt": "0.5",
   "plt": "Rare",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Health",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Stamina Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Damage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fear",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Collected from dead Dremora."
  },
  {
   "idx": 22,
   "nam": "Deathbell",
   "val": "4",
   "wgt": "0.1",
   "plt": "Rare",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Health",
     "val": 1,
     "mag": "1.5",
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Ravage Stamina",
     "val": "2.1",
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Slow",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Weakness to Poison",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Harvested from Deathbell, found in Hjaalmarch."
  },
  {
   "idx": 23,
   "nam": "Dragon's Tongue",
   "val": "5",
   "wgt": "0.1",
   "plt": "Common",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Resist Fire",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Barter",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Illusion",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Two-handed",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from Dragon's Tongue, found in the volcanic tundra of Eastmarch."
  },
  {
   "idx": 24,
   "nam": "Dwarven Oil",
   "val": "15",
   "wgt": "0.25",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Weakness to Magic",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Illusion",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Regenerate Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Restore Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from destroyed Dwarven Automatons, found in Dwarven Ruins."
  },
  {
   "idx": 25,
   "nam": "Ectoplasm",
   "val": "25",
   "wgt": "0.1",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Destruction",
     "val": 1,
     "mag": "0.8",
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Collected from undead Ghosts."
  },
  {
   "idx": 26,
   "nam": "Elves Ear",
   "val": "10",
   "wgt": "0.1",
   "plt": "Common",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Marksman",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Weakness to Frost",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Resist Fire",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from Dried Elves Ear bunches found in homes and camps."
  },
  {
   "idx": 27,
   "nam": "Eye of Sabre Cat",
   "val": "2",
   "wgt": "0.1",
   "plt": "None (Uncommon)",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Ravage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Damage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Restore Health",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from dead Sabre Cats."
  },
  {
   "idx": 28,
   "nam": "Falmer Ear",
   "val": "10",
   "wgt": "0.2",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Frenzy",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Resist Poison",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Lockpicking",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from dead Falmer."
  },
  {
   "idx": 29,
   "nam": "Fire Salts",
   "val": "50",
   "wgt": "0.25",
   "plt": "Rare",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Weakness to Frost",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Resist Fire",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Restore Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Regenerate Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from dead Flame Atronachs, a type of daedra."
  },
  {
   "idx": 30,
   "nam": "Fly Amanita",
   "val": "2",
   "wgt": "0.1",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Resist Fire",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Two-handed",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Frenzy",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Regenerate Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from Fly Amanita mushrooms, found in various caves."
  },
  {
   "idx": 31,
   "nam": "Frost Mirriam",
   "val": "1",
   "wgt": "0.1",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Resist Frost",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Sneak",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Ravage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Damage Stamina Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Harvested from Dried Frost Mirriam bunches found in homes and camps."
  },
  {
   "idx": 32,
   "nam": "Frost Salts",
   "val": "100",
   "wgt": "0.25",
   "plt": "Rare",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Weakness to Fire",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Resist Frost",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Restore Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Conjuration",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from dead Frost Atronachs, a type of daedra."
  },
  {
   "idx": 33,
   "nam": "Garlic",
   "val": "1",
   "wgt": "0.25",
   "plt": "Common",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Resist Poison",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Regenerate Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Regenerate Health",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Food. Can also be harvested from Garlic Braids."
  },
  {
   "idx": 34,
   "nam": "Giant Lichen",
   "val": "5",
   "wgt": "0.25",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Weakness to Shock",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Ravage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Weakness to Poison",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Restore Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from Giant Lichen, found in Hjaalmarch."
  },
  {
   "idx": 35,
   "nam": "Giant's Toe",
   "val": "20",
   "wgt": "1",
   "plt": "Rare",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Health",
     "val": "5.9",
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Carry Weight",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Stamina Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Collected from dead Giants, which can be found in Giant Camps."
  },
  {
   "idx": 36,
   "nam": "Gleamblossom",
   "val": "5",
   "wgt": "0.1",
   "plt": "None",
   "dlc": "DG",
   "eff": [
    {
     "idx": -1,
     "nam": "Resist Magic",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fear",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Regenerate Health",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Paralysis",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Harvested from the plant of the same name."
  },
  {
   "idx": 37,
   "nam": "Glow Dust",
   "val": "20",
   "wgt": "0.5",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Damage Magicka Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Destruction",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Resist Shock",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from dead Wisps and Wispmothers."
  },
  {
   "idx": 38,
   "nam": "Glowing Mushroom",
   "val": "5",
   "wgt": "0.2",
   "plt": "None",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Resist Shock",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Destruction",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Smithing",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Health",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from Glowing Mushrooms, found in various caves."
  },
  {
   "idx": 39,
   "nam": "Grass Pod",
   "val": "1",
   "wgt": "0.1",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Resist Poison",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Ravage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Alteration",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Restore Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from Spiky Grass, found in northern regions of Skyrim."
  },
  {
   "idx": 40,
   "nam": "Hagraven Claw",
   "val": "20",
   "wgt": "0.25",
   "plt": "Rare",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Resist Magic",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Lingering Damage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Enchanting",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Barter",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from dead Hagravens."
  },
  {
   "idx": 41,
   "nam": "Hagraven Feathers",
   "val": "20",
   "wgt": "0.1",
   "plt": "Rare",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Conjuration",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Frenzy",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Weakness to Shock",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Collected from dead Hagravens. Can also be found scattered around their sleeping areas."
  },
  {
   "idx": 42,
   "nam": "Hanging Moss",
   "val": "1",
   "wgt": "0.25",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Health",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Magicka Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify One-handed",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from Hanging Moss."
  },
  {
   "idx": 43,
   "nam": "Hawk Beak",
   "val": "15",
   "wgt": "0.25",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Resist Frost",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Carry Weight",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Resist Shock",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from dead Hawks."
  },
  {
   "idx": 44,
   "nam": "Hawk Feathers",
   "val": "15",
   "wgt": "0.1",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Light Armor",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify One-handed",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Sneak",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from dead Hawks."
  },
  {
   "idx": 45,
   "nam": "Hawk's Egg",
   "val": "5",
   "wgt": "0.5",
   "plt": "None",
   "dlc": "HF",
   "eff": [
    {
     "idx": -1,
     "nam": "Resist Magic",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Magicka Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Waterbreathing",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Lingering Damage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Harvested from Hawk nests."
  },
  {
   "idx": 46,
   "nam": "Histcarp",
   "val": "6",
   "wgt": "0.25",
   "plt": "Common",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Stamina Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Waterbreathing",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected by catching Histcarp fish."
  },
  {
   "idx": 47,
   "nam": "Honeycomb",
   "val": "5",
   "wgt": "1",
   "plt": "None (Common)",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Block",
     "val": 1,
     "mag": "0.5",
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Light Armor",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Ravage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Food. Collected from beehives."
  },
  {
   "idx": 48,
   "nam": "Human Flesh",
   "val": "1",
   "wgt": "0.25",
   "plt": "None",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Paralysis",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Restore Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Sneak",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Cannot be harvested or collected; with the Dawnguard plug-in installed, several respawning samples can be found in Volkihar Keep."
  },
  {
   "idx": 49,
   "nam": "Human Heart",
   "val": "0",
   "wgt": "1",
   "plt": "None",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Damage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Damage Magicka Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Frenzy",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Cannot be harvested or collected; limited number of samples available."
  },
  {
   "idx": 50,
   "nam": "Ice Wraith Teeth",
   "val": "30",
   "wgt": "0.25",
   "plt": "Rare",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Weakness to Frost",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Heavy Armor",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Invisibility",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Weakness to Fire",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Collected from Ice Wraiths."
  },
  {
   "idx": 51,
   "nam": "Imp Stool",
   "val": "0",
   "wgt": "0.3",
   "plt": "Rare",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Lingering Damage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Paralysis",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Restore Health",
     "val": 1,
     "mag": "0.6",
     "lix": true
    }
   ],
   "src": "Harvested from Imp Stool mushrooms, found in various caves."
  },
  {
   "idx": 52,
   "nam": "Jazbay Grapes",
   "val": "1",
   "wgt": "0.2",
   "plt": "Rare",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Weakness to Magic",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Regenerate Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Ravage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Harvested from Jazbay vines, found in the volcanic tundra of Eastmarch."
  },
  {
   "idx": 53,
   "nam": "Juniper Berries",
   "val": "1",
   "wgt": "0.1",
   "plt": "Common",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Weakness to Fire",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Marksman",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Regenerate Health",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Stamina Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Harvested from Juniper shrubs, common in The Reach."
  },
  {
   "idx": 54,
   "nam": "Large Antlers",
   "val": "2",
   "wgt": "0.1",
   "plt": "None (Uncommon)",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Slow",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Damage Stamina Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Collected from dead male Elk."
  },
  {
   "idx": 55,
   "nam": "Lavender",
   "val": "1",
   "wgt": "0.1",
   "plt": "Common",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Resist Magic",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Ravage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Conjuration",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from Lavender, most common in Whiterun Hold."
  },
  {
   "idx": 56,
   "nam": "Luna Moth Wing",
   "val": "5",
   "wgt": "0.1",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Light Armor",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Regenerate Health",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Invisibility",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected by catching Luna Moths. Often found near flowers after dark."
  },
  {
   "idx": 57,
   "nam": "Moon Sugar",
   "val": "50",
   "wgt": "0.25",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Weakness to Fire",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Resist Frost",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Restore Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Regenerate Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Cannot be collected or harvested. Can be purchased from the Khajiit Traders."
  },
  {
   "idx": 58,
   "nam": "Mora Tapinella",
   "val": "4",
   "wgt": "0.25",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Lingering Damage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Regenerate Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Illusion",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from Mora Tapinella mushrooms, found growing on dead trees."
  },
  {
   "idx": 59,
   "nam": "Mudcrab Chitin",
   "val": "2",
   "wgt": "0.25",
   "plt": "None (Common)",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Resist Poison",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Resist Fire",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from dead Mudcrabs, found in or near bodies of water."
  },
  {
   "idx": 60,
   "nam": "Namira's Rot",
   "val": "0",
   "wgt": "0.25",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Lockpicking",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fear",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Regenerate Health",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from Namira's Rot mushrooms, found in various caves."
  },
  {
   "idx": 61,
   "nam": "Nightshade",
   "val": "8",
   "wgt": "0.1",
   "plt": "Rare",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Damage Magicka Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Lingering Damage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Destruction",
     "val": 1,
     "mag": "0.8",
     "lix": true
    }
   ],
   "src": "Harvested from Nightshade, found growing throughout Skyrim."
  },
  {
   "idx": 62,
   "nam": "Nirnroot",
   "val": "10",
   "wgt": "0.2",
   "plt": "Rare",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Health",
     "val": "12.6",
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Damage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Invisibility",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Resist Magic",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from Nirnroot, found near bodies of water throughout Skyrim."
  },
  {
   "idx": 63,
   "nam": "Nordic Barnacle",
   "val": "5",
   "wgt": "0.2",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Waterbreathing",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Regenerate Health",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Pickpocket",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from Nordic Barnacle Clusters, found in or near water."
  },
  {
   "idx": 64,
   "nam": "Orange Dartwing",
   "val": "1",
   "wgt": "0.1",
   "plt": "None (Common)",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Ravage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Pickpocket",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Lingering Damage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Collected by catching Dragonflies found near rivers and streams below the snow line."
  },
  {
   "idx": 65,
   "nam": "Pearl",
   "val": "2",
   "wgt": "0.1",
   "plt": "None (Uncommon)",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Block",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Restore Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Resist Shock",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Cannot be harvested or collected in the original version of the game; only readily available after the Merchant perk has been unlocked. With Dragonborn, they can be harvested from Pearl Oysters in Solstheim."
  },
  {
   "idx": 66,
   "nam": "Pine Thrush Egg",
   "val": "2",
   "wgt": "0.5",
   "plt": "Common",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Lockpicking",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Weakness to Poison",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Resist Shock",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from bird nests in forested regions, in particular The Rift."
  },
  {
   "idx": 67,
   "nam": "Poison Bloom",
   "val": "5",
   "wgt": "0.25",
   "plt": "None",
   "dlc": "DG",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Health",
     "val": 1,
     "mag": "1.5",
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Slow",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Carry Weight",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fear",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Harvested from the plant of the same name."
  },
  {
   "idx": 68,
   "nam": "Powdered Mammoth Tusk",
   "val": "2",
   "wgt": "0.1",
   "plt": "None (Uncommon)",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Sneak",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Weakness to Fire",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fear",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Cannot be harvested or collected; only readily available after the Merchant perk has been unlocked."
  },
  {
   "idx": 69,
   "nam": "Purple Mountain Flower",
   "val": "2",
   "wgt": "0.1",
   "plt": "Common",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Sneak",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Lingering Damage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Resist Frost",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from the purple variety of Mountain Flower."
  },
  {
   "idx": 70,
   "nam": "Red Mountain Flower",
   "val": "2",
   "wgt": "0.1",
   "plt": "Common",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Ravage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Harvested from the red variety of Mountain Flower."
  },
  {
   "idx": 71,
   "nam": "River Betty",
   "val": "15",
   "wgt": "0.25",
   "plt": "Common",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Health",
     "val": 1,
     "mag": "2.5",
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Alteration",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Slow",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Carry Weight",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected by catching River Betty fish."
  },
  {
   "idx": 72,
   "nam": "Rock Warbler Egg",
   "val": "2",
   "wgt": "0.5",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Health",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify One-handed",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Weakness to Magic",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Harvested from bird nests in rocky regions, in particular The Reach."
  },
  {
   "idx": 73,
   "nam": "Sabre Cat Tooth",
   "val": "2",
   "wgt": "0.1",
   "plt": "None (Uncommon)",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Heavy Armor",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Smithing",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Weakness to Poison",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Collected from dead Sabre cats."
  },
  {
   "idx": 74,
   "nam": "Salmon Roe",
   "val": "5",
   "wgt": "0.2",
   "plt": "None",
   "dlc": "HF",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Stamina",
     "val": 1,
     "mag": "0.4",
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Waterbreathing",
     "val": "15.4",
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Magicka",
     "val": "12.5",
     "mag": "1.05",
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Regenerate Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from jumping Salmon."
  },
  {
   "idx": 75,
   "nam": "Salt Pile",
   "val": "2",
   "wgt": "0.2",
   "plt": "Common",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Weakness to Magic",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Restoration",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Slow",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Regenerate Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Food. Cannot be harvested or collected, but is commonly found in barrels and sacks."
  },
  {
   "idx": 76,
   "nam": "Scaly Pholiota",
   "val": "4",
   "wgt": "0.25",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Weakness to Magic",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Illusion",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Regenerate Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Carry Weight",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from Scaly Pholiota mushrooms, found growing on dead trees."
  },
  {
   "idx": 77,
   "nam": "Silverside Perch",
   "val": "15",
   "wgt": "0.25",
   "plt": "Common",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Stamina Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Ravage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Resist Frost",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected by catching Silverside Perch fish."
  },
  {
   "idx": 78,
   "nam": "Skeever Tail",
   "val": "3",
   "wgt": "0.2",
   "plt": "Common",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Stamina Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Ravage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Damage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Light Armor",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from dead Skeevers."
  },
  {
   "idx": 79,
   "nam": "Slaughterfish Egg",
   "val": "3",
   "wgt": "0.2",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Resist Poison",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Pickpocket",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Lingering Damage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from Slaughterfish Egg Nests, found in or near water."
  },
  {
   "idx": 80,
   "nam": "Slaughterfish Scales",
   "val": "3",
   "wgt": "0.1",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Resist Frost",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Lingering Damage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Heavy Armor",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Block",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from dead Slaughterfish."
  },
  {
   "idx": 81,
   "nam": "Small Antlers",
   "val": "2",
   "wgt": "0.1",
   "plt": "None (Common)",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Weakness to Poison",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Restoration",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Lingering Damage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Damage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Collected from dead female Elk."
  },
  {
   "idx": 82,
   "nam": "Small Pearl",
   "val": "2",
   "wgt": "0.1",
   "plt": "None (Uncommon)",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify One-handed",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Restoration",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Resist Frost",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Cannot be harvested or collected in the original version of the game; only readily available after the Merchant perk has been unlocked. With Dragonborn, they can be harvested from Pearl Oysters in Solstheim."
  },
  {
   "idx": 83,
   "nam": "Snowberries",
   "val": "4",
   "wgt": "0.1",
   "plt": "Common",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Resist Fire",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Enchanting",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Resist Frost",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Resist Shock",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from Snowberry bushes, found in snowy regions of Skyrim."
  },
  {
   "idx": 84,
   "nam": "Spider Egg",
   "val": "5",
   "wgt": "0.2",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Damage Magicka Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Lockpicking",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Marksman",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from spider Egg Sacs and Web Sacs."
  },
  {
   "idx": 85,
   "nam": "Spriggan Sap",
   "val": "15",
   "wgt": "0.2",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Magicka Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Enchanting",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Smithing",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Alteration",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Cannot be harvested or collected; best source is merchants."
  },
  {
   "idx": 86,
   "nam": "Swamp Fungal Pod",
   "val": "5",
   "wgt": "0.25",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Resist Shock",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Lingering Damage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Paralysis",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Restore Health",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from Swamp Fungal Pod, common in the tundra marsh of Hjaalmarch."
  },
  {
   "idx": 87,
   "nam": "Taproot",
   "val": "15",
   "wgt": "0.5",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Weakness to Magic",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Illusion",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Regenerate Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Restore Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from dead Spriggans."
  },
  {
   "idx": 88,
   "nam": "Thistle Branch",
   "val": "1",
   "wgt": "0.1",
   "plt": "Common",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Resist Frost",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Ravage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Resist Poison",
     "val": 1,
     "mag": "0.75",
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Heavy Armor",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from Thistle."
  },
  {
   "idx": 89,
   "nam": "Torchbug Thorax",
   "val": "1",
   "wgt": "0.1",
   "plt": "None (Common)",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Lingering Damage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Weakness to Magic",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected by catching Torchbugs. Found below the snowline after dark."
  },
  {
   "idx": 90,
   "nam": "Troll Fat",
   "val": "15",
   "wgt": "1",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Resist Poison",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Two-handed",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Frenzy",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Damage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Collected from dead Trolls."
  },
  {
   "idx": 91,
   "nam": "Tundra Cotton",
   "val": "1",
   "wgt": "0.1",
   "plt": "Common",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Resist Magic",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Block",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Barter",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from Tundra Cotton, found in Whiterun Hold."
  },
  {
   "idx": 92,
   "nam": "Vampire Dust",
   "val": "25",
   "wgt": "0.2",
   "plt": "Rare",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Invisibility",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Restore Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Regenerate Health",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from dead Vampires."
  },
  {
   "idx": 93,
   "nam": "Void Salts",
   "val": "125",
   "wgt": "0.2",
   "plt": "Rare",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Weakness to Shock",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Resist Magic",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from dead Storm Atronachs."
  },
  {
   "idx": 94,
   "nam": "Wheat",
   "val": "5",
   "wgt": "0.1",
   "plt": "Common",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Health",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Health",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Stamina Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Lingering Damage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Food. Harvested from wheat bushels, found in various farms."
  },
  {
   "idx": 95,
   "nam": "White Cap",
   "val": "0",
   "wgt": "0.3",
   "plt": "Uncommon",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Weakness to Frost",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Heavy Armor",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Restore Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Ravage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Harvested from White Cap mushrooms, found in various caves."
  },
  {
   "idx": 96,
   "nam": "Wisp Wrappings",
   "val": "2",
   "wgt": "0.1",
   "plt": "None (Uncommon)",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Stamina",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Destruction",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Carry Weight",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Resist Magic",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from dead Wispmothers."
  },
  {
   "idx": 97,
   "nam": "Yellow Mountain Flower",
   "val": "2",
   "wgt": "0.1",
   "plt": "None",
   "dlc": "DG",
   "eff": [
    {
     "idx": -1,
     "nam": "Resist Poison",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Restoration",
     "val": 1,
     "mag": "1.25",
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Health",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Stamina Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Harvested from the yellow variety of Mountain Flower."
  },
  {
   "idx": 98,
   "nam": "Berit's Ashes",
   "val": "5",
   "wgt": "0.2",
   "plt": "None",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Resist Fire",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Conjuration",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Ravage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "This ingredient is given as a quest item. Its effects are all identical to standard Bone Meal."
  },
  {
   "idx": 99,
   "nam": "Farengar's Frost Salt",
   "val": "100",
   "wgt": "0.25",
   "plt": "None",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Weakness to Fire",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Resist Frost",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Restore Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Conjuration",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "This ingredient is given as a quest item. It is identical to standard Frost Salts, except for its name."
  },
  {
   "idx": 100,
   "nam": "Fine-Cut Void Salts",
   "val": "125",
   "wgt": "0.2",
   "plt": "None",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Weakness to Shock",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Resist Magic",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "This ingredient is given as a quest item. It is identical to standard Void Salts, except for its name."
  },
  {
   "idx": 101,
   "nam": "Jarrin Root",
   "val": "10",
   "wgt": "0.5",
   "plt": "None",
   "dlc": "none",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Health",
     "val": 1,
     "mag": "100",
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Damage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Damage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Damage Magicka Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "You may only receive this ingredient once during the Dark Brotherhood quest line."
  },
  {
   "idx": 102,
   "nam": "Ash Creep Cluster",
   "val": "20",
   "wgt": "0.25",
   "plt": "",
   "dlc": "DB",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Invisibility",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Resist Fire",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Destruction",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from creep cluster plants unique to Solstheim."
  },
  {
   "idx": 103,
   "nam": "Ash Hopper Jelly",
   "val": "20",
   "wgt": "0.25",
   "plt": "",
   "dlc": "DB",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Health",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Light Armor",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Resist Shock",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Weakness to Frost",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Collected from dead ash hoppers."
  },
  {
   "idx": 104,
   "nam": "Ashen Grass Pod",
   "val": "1",
   "wgt": "0.1",
   "plt": "",
   "dlc": "DB",
   "eff": [
    {
     "idx": -1,
     "nam": "Resist Fire",
     "val": 1,
     "mag": "1.34",
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Weakness to Shock",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Lockpicking",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Sneak",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from spiky grass plants unique to Solstheim."
  },
  {
   "idx": 105,
   "nam": "Boar Tusk",
   "val": "20",
   "wgt": "0.5",
   "plt": "",
   "dlc": "DB",
   "eff": [
    {
     "idx": -1,
     "nam": "Fortify Stamina",
     "val": "1.25",
     "mag": "5.9",
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Health",
     "val": "5.9",
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Block",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Frenzy",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Collected from dead bristlebacks and rieklings."
  },
  {
   "idx": 106,
   "nam": "Burnt Spriggan Wood",
   "val": "20",
   "wgt": "0.5",
   "plt": "",
   "dlc": "DB",
   "eff": [
    {
     "idx": -1,
     "nam": "Weakness to Fire",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Alteration",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Magicka Regen",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Slow",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Collected from dead burnt spriggans."
  },
  {
   "idx": 107,
   "nam": "Emperor Parasol Moss",
   "val": "1",
   "wgt": "0.25",
   "plt": "",
   "dlc": "DB",
   "eff": [
    {
     "idx": -1,
     "nam": "Damage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Magicka",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Regenerate Health",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Two-handed",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Harvested from emperor parasol moss plants near Tel Mithryn."
  },
  {
   "idx": 108,
   "nam": "Felsaad Tern Feathers",
   "val": "15",
   "wgt": "0.1",
   "plt": "",
   "dlc": "DB",
   "eff": [
    {
     "idx": -1,
     "nam": "Restore Health",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Light Armor",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Resist Magic",
     "val": 1,
     "mag": 1,
     "lix": true
    }
   ],
   "src": "Collected from dead Felsaad terns."
  },
  {
   "idx": 109,
   "nam": "Netch Jelly",
   "val": "20",
   "wgt": "0.5",
   "plt": "",
   "dlc": "DB",
   "eff": [
    {
     "idx": -1,
     "nam": "Paralysis",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Carry Weight",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Restore Stamina",
     "val": 1,
     "mag": "2",
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fear",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Collected from dead netch."
  },
  {
   "idx": 110,
   "nam": "Scathecraw",
   "val": "1",
   "wgt": "0.1",
   "plt": "",
   "dlc": "DB",
   "eff": [
    {
     "idx": -1,
     "nam": "Ravage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Ravage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Ravage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Lingering Damage Health",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Harvested from scathecraw plants."
  },
  {
   "idx": 111,
   "nam": "Spawn Ash",
   "val": "20",
   "wgt": "0.1",
   "plt": "",
   "dlc": "DB",
   "eff": [
    {
     "idx": -1,
     "nam": "Ravage Stamina",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Resist Fire",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Fortify Enchanting",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Ravage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Collected from dead ash spawn."
  },
  {
   "idx": 112,
   "nam": "Trama Root",
   "val": "1",
   "wgt": "0.2",
   "plt": "",
   "dlc": "DB",
   "eff": [
    {
     "idx": -1,
     "nam": "Weakness to Shock",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Fortify Carry Weight",
     "val": 1,
     "mag": 1,
     "lix": true
    },
    {
     "idx": -1,
     "nam": "Damage Magicka",
     "val": 1,
     "mag": 1,
     "lix": false
    },
    {
     "idx": -1,
     "nam": "Slow",
     "val": 1,
     "mag": 1,
     "lix": false
    }
   ],
   "src": "Harvested from trama root plants."
  }
 ],
 "ingN": {
  "Abecean Longfin": 0,
  "Ancestor Moth Wing": 1,
  "Bear Claws": 2,
  "Bee": 3,
  "Beehive Husk": 4,
  "Bleeding Crown": 5,
  "Blisterwort": 6,
  "Blue Butterfly Wing": 7,
  "Blue Dartwing": 8,
  "Blue Mountain Flower": 9,
  "Bone Meal": 10,
  "Briar Heart": 11,
  "Butterfly Wing": 12,
  "Canis Root": 13,
  "Charred Skeever Hide": 14,
  "Chaurus Eggs": 15,
  "Chaurus Hunter Antennae": 16,
  "Chicken's Egg": 17,
  "Creep Cluster": 18,
  "Crimson Nirnroot": 19,
  "Cyrodilic Spadetail": 20,
  "Daedra Heart": 21,
  "Deathbell": 22,
  "Dragon's Tongue": 23,
  "Dwarven Oil": 24,
  "Ectoplasm": 25,
  "Elves Ear": 26,
  "Eye of Sabre Cat": 27,
  "Falmer Ear": 28,
  "Fire Salts": 29,
  "Fly Amanita": 30,
  "Frost Mirriam": 31,
  "Frost Salts": 32,
  "Garlic": 33,
  "Giant Lichen": 34,
  "Giant's Toe": 35,
  "Gleamblossom": 36,
  "Glow Dust": 37,
  "Glowing Mushroom": 38,
  "Grass Pod": 39,
  "Hagraven Claw": 40,
  "Hagraven Feathers": 41,
  "Hanging Moss": 42,
  "Hawk Beak": 43,
  "Hawk Feathers": 44,
  "Hawk's Egg": 45,
  "Histcarp": 46,
  "Honeycomb": 47,
  "Human Flesh": 48,
  "Human Heart": 49,
  "Ice Wraith Teeth": 50,
  "Imp Stool": 51,
  "Jazbay Grapes": 52,
  "Juniper Berries": 53,
  "Large Antlers": 54,
  "Lavender": 55,
  "Luna Moth Wing": 56,
  "Moon Sugar": 57,
  "Mora Tapinella": 58,
  "Mudcrab Chitin": 59,
  "Namira's Rot": 60,
  "Nightshade": 61,
  "Nirnroot": 62,
  "Nordic Barnacle": 63,
  "Orange Dartwing": 64,
  "Pearl": 65,
  "Pine Thrush Egg": 66,
  "Poison Bloom": 67,
  "Powdered Mammoth Tusk": 68,
  "Purple Mountain Flower": 69,
  "Red Mountain Flower": 70,
  "River Betty": 71,
  "Rock Warbler Egg": 72,
  "Sabre Cat Tooth": 73,
  "Salmon Roe": 74,
  "Salt Pile": 75,
  "Scaly Pholiota": 76,
  "Silverside Perch": 77,
  "Skeever Tail": 78,
  "Slaughterfish Egg": 79,
  "Slaughterfish Scales": 80,
  "Small Antlers": 81,
  "Small Pearl": 82,
  "Snowberries": 83,
  "Spider Egg": 84,
  "Spriggan Sap": 85,
  "Swamp Fungal Pod": 86,
  "Taproot": 87,
  "Thistle Branch": 88,
  "Torchbug Thorax": 89,
  "Troll Fat": 90,
  "Tundra Cotton": 91,
  "Vampire Dust": 92,
  "Void Salts": 93,
  "Wheat": 94,
  "White Cap": 95,
  "Wisp Wrappings": 96,
  "Yellow Mountain Flower": 97,
  "Berit's Ashes": 98,
  "Farengar's Frost Salt": 99,
  "Fine-Cut Void Salts": 100,
  "Jarrin Root": 101,
  "Ash Creep Cluster": 102,
  "Ash Hopper Jelly": 103,
  "Ashen Grass Pod": 104,
  "Boar Tusk": 105,
  "Burnt Spriggan Wood": 106,
  "Emperor Parasol Moss": 107,
  "Felsaad Tern Feathers": 108,
  "Netch Jelly": 109,
  "Scathecraw": 110,
  "Spawn Ash": 111,
  "Trama Root": 112
 },
 "metrics": {
  "ing": {
   "dlc": {
    "none": 95,
    "DG": 5,
    "HF": 2,
    "DB": 11
   },
   "plt": {
    "Common": 22,
    "None": 15,
    "None (Uncommon)": 9,
    "None (Common)": 6,
    "Uncommon": 35,
    "Rare": 15,
    "": 11
   }
  }
 },
 "ii": {},
 "ep": [],
 "ei": {}
}
);}

