/* autogenerated content -- DO NOT MODIFY
 * to change this data you must:
 * 1. edit scripts/parser.js
 * 2. load parser.html
 * 3. paste the content into scripts/index.js
 */

function getIdx() { return({
 "ing": {
  "num": {
   "Abecean Longfin": 0,
   "Ancestor Moth Wing": 1,
   "Ash Creep Cluster": 2,
   "Ash Hopper Jelly": 3,
   "Ashen Grass Pod": 4,
   "Bear Claws": 5,
   "Bee": 6,
   "Beehive Husk": 7,
   "Berit's Ashes": 8,
   "Bleeding Crown": 9,
   "Blisterwort": 10,
   "Blue Butterfly Wing": 11,
   "Blue Dartwing": 12,
   "Blue Mountain Flower": 13,
   "Boar Tusk": 14,
   "Bone Meal": 15,
   "Briar Heart": 16,
   "Burnt Spriggan Wood": 17,
   "Butterfly Wing": 18,
   "Canis Root": 19,
   "Charred Skeever Hide": 20,
   "Chaurus Eggs": 21,
   "Chaurus Hunter Antennae": 22,
   "Chicken's Egg": 23,
   "Creep Cluster": 24,
   "Crimson Nirnroot": 25,
   "Cyrodilic Spadetail": 26,
   "Daedra Heart": 27,
   "Deathbell": 28,
   "Dragon's Tongue": 29,
   "Dwarven Oil": 30,
   "Ectoplasm": 31,
   "Elves Ear": 32,
   "Emperor Parasol Moss": 33,
   "Eye of Sabre Cat": 34,
   "Falmer Ear": 35,
   "Farengar's Frost Salt": 36,
   "Felsaad Tern Feathers": 37,
   "Fine-Cut Void Salts": 38,
   "Fire Salts": 39,
   "Fly Amanita": 40,
   "Frost Mirriam": 41,
   "Frost Salts": 42,
   "Garlic": 43,
   "Giant's Toe": 44,
   "Giant Lichen": 45,
   "Gleamblossom": 46,
   "Glow Dust": 47,
   "Glowing Mushroom": 48,
   "Grass Pod": 49,
   "Hagraven Claw": 50,
   "Hagraven Feathers": 51,
   "Hanging Moss": 52,
   "Hawk's Egg": 53,
   "Hawk Beak": 54,
   "Hawk Feathers": 55,
   "Histcarp": 56,
   "Honeycomb": 57,
   "Human Flesh": 58,
   "Human Heart": 59,
   "Ice Wraith Teeth": 60,
   "Imp Stool": 61,
   "Jarrin Root": 62,
   "Jazbay Grapes": 63,
   "Juniper Berries": 64,
   "Large Antlers": 65,
   "Lavender": 66,
   "Luna Moth Wing": 67,
   "Moon Sugar": 68,
   "Mora Tapinella": 69,
   "Mudcrab Chitin": 70,
   "Namira's Rot": 71,
   "Netch Jelly": 72,
   "Nightshade": 73,
   "Nirnroot": 74,
   "Nordic Barnacle": 75,
   "Orange Dartwing": 76,
   "Pearl": 77,
   "Pine Thrush Egg": 78,
   "Poison Bloom": 79,
   "Powdered Mammoth Tusk": 80,
   "Purple Mountain Flower": 81,
   "Red Mountain Flower": 82,
   "River Betty": 83,
   "Rock Warbler Egg": 84,
   "Sabre Cat Tooth": 85,
   "Salmon Roe": 86,
   "Salt Pile": 87,
   "Scaly Pholiota": 88,
   "Scathecraw": 89,
   "Silverside Perch": 90,
   "Skeever Tail": 91,
   "Slaughterfish Egg": 92,
   "Slaughterfish Scales": 93,
   "Small Antlers": 94,
   "Small Pearl": 95,
   "Snowberries": 96,
   "Spawn Ash": 97,
   "Spider Egg": 98,
   "Spriggan Sap": 99,
   "Swamp Fungal Pod": 100,
   "Taproot": 101,
   "Thistle Branch": 102,
   "Torchbug Thorax": 103,
   "Trama Root": 104,
   "Troll Fat": 105,
   "Tundra Cotton": 106,
   "Vampire Dust": 107,
   "Void Salts": 108,
   "Wheat": 109,
   "White Cap": 110,
   "Wisp Wrappings": 111,
   "Yellow Mountain Flower": 112
  },
  "lab": [
   {
    "idx": 0,
    "nam": "Abecean Longfin",
    "val": "15",
    "wgt": "0.5",
    "plt": "Common",
    "dlc": "none",
    "eff": [
     {
      "idx": 51,
      "nam": "Weakness to Frost",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 25,
      "nam": "Fortify Sneak",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 53,
      "nam": "Weakness to Poison",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 23,
      "nam": "Fortify Restoration",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected by catching Abacean Longfin fish."
   },
   {
    "idx": 1,
    "nam": "Ancestor Moth Wing",
    "val": "2",
    "wgt": "0.1",
    "plt": "None",
    "dlc": "DG",
    "eff": [
     {
      "idx": 5,
      "nam": "Damage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 11,
      "nam": "Fortify Conjuration",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 2,
      "nam": "Damage Magicka Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 13,
      "nam": "Fortify Enchanting",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected by catching Ancestor Moths."
   },
   {
    "idx": 2,
    "nam": "Ash Creep Cluster",
    "val": "20",
    "wgt": "0.25",
    "plt": "",
    "dlc": "DB",
    "eff": [
     {
      "idx": 5,
      "nam": "Damage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 29,
      "nam": "Invisibility",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 40,
      "nam": "Resist Fire",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 12,
      "nam": "Fortify Destruction",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from creep cluster plants unique to Solstheim."
   },
   {
    "idx": 3,
    "nam": "Ash Hopper Jelly",
    "val": "20",
    "wgt": "0.25",
    "plt": "",
    "dlc": "DB",
    "eff": [
     {
      "idx": 45,
      "nam": "Restore Health",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 17,
      "nam": "Fortify Light Armor",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 44,
      "nam": "Resist Shock",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 51,
      "nam": "Weakness to Frost",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Collected from dead ash hoppers."
   },
   {
    "idx": 4,
    "nam": "Ashen Grass Pod",
    "val": "1",
    "wgt": "0.1",
    "plt": "",
    "dlc": "DB",
    "eff": [
     {
      "idx": 40,
      "nam": "Resist Fire",
      "val": 1,
      "mag": "1.34",
      "lix": true
     },
     {
      "idx": 54,
      "nam": "Weakness to Shock",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 18,
      "nam": "Fortify Lockpicking",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 25,
      "nam": "Fortify Sneak",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from spiky grass plants unique to Solstheim."
   },
   {
    "idx": 5,
    "nam": "Bear Claws",
    "val": "2",
    "wgt": "0.1",
    "plt": "None (Uncommon)",
    "dlc": "none",
    "eff": [
     {
      "idx": 47,
      "nam": "Restore Stamina",
      "val": 1,
      "mag": "0.8",
      "lix": true
     },
     {
      "idx": 14,
      "nam": "Fortify Health",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 21,
      "nam": "Fortify One-handed",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 2,
      "nam": "Damage Magicka Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Collected from various types of dead Bears."
   },
   {
    "idx": 6,
    "nam": "Bee",
    "val": "3",
    "wgt": "0.1",
    "plt": "Common",
    "dlc": "none",
    "eff": [
     {
      "idx": 47,
      "nam": "Restore Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 36,
      "nam": "Ravage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 39,
      "nam": "Regenerate Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 54,
      "nam": "Weakness to Shock",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Collected from beehives and by catching Bees."
   },
   {
    "idx": 7,
    "nam": "Beehive Husk",
    "val": "5",
    "wgt": "1",
    "plt": "None (Common)",
    "dlc": "none",
    "eff": [
     {
      "idx": 43,
      "nam": "Resist Poison",
      "val": 1,
      "mag": "0.5",
      "lix": true
     },
     {
      "idx": 17,
      "nam": "Fortify Light Armor",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 25,
      "nam": "Fortify Sneak",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 12,
      "nam": "Fortify Destruction",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from beehives."
   },
   {
    "idx": 8,
    "nam": "Berit's Ashes",
    "val": "5",
    "wgt": "0.2",
    "plt": "None",
    "dlc": "none",
    "eff": [
     {
      "idx": 5,
      "nam": "Damage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 40,
      "nam": "Resist Fire",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 11,
      "nam": "Fortify Conjuration",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 36,
      "nam": "Ravage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "This ingredient is given as a quest item. Its effects are all identical to standard Bone Meal."
   },
   {
    "idx": 9,
    "nam": "Bleeding Crown",
    "val": "10",
    "wgt": "0.3",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 50,
      "nam": "Weakness to Fire",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 9,
      "nam": "Fortify Block",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 53,
      "nam": "Weakness to Poison",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 42,
      "nam": "Resist Magic",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from Bleeding Crown, a mushroom found in various caves."
   },
   {
    "idx": 10,
    "nam": "Blisterwort",
    "val": "12",
    "wgt": "0.2",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 5,
      "nam": "Damage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 28,
      "nam": "Frenzy",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 45,
      "nam": "Restore Health",
      "val": 1,
      "mag": "0.6",
      "lix": true
     },
     {
      "idx": 24,
      "nam": "Fortify Smithing",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from Blisterwort mushrooms found in various caves."
   },
   {
    "idx": 11,
    "nam": "Blue Butterfly Wing",
    "val": "2",
    "wgt": "0.1",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 5,
      "nam": "Damage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 11,
      "nam": "Fortify Conjuration",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 2,
      "nam": "Damage Magicka Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 13,
      "nam": "Fortify Enchanting",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected by catching Blue Butterflies. Often found during daylight hours near flowering plants."
   },
   {
    "idx": 12,
    "nam": "Blue Dartwing",
    "val": "1",
    "wgt": "0.1",
    "plt": "None (Uncommon)",
    "dlc": "none",
    "eff": [
     {
      "idx": 44,
      "nam": "Resist Shock",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 22,
      "nam": "Fortify Pickpocket",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 45,
      "nam": "Restore Health",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 6,
      "nam": "Fear",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Collected by catching Dragonflies found near rivers and streams below the snow line."
   },
   {
    "idx": 13,
    "nam": "Blue Mountain Flower",
    "val": "2",
    "wgt": "0.1",
    "plt": "Common",
    "dlc": "none",
    "eff": [
     {
      "idx": 45,
      "nam": "Restore Health",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 11,
      "nam": "Fortify Conjuration",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 14,
      "nam": "Fortify Health",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 2,
      "nam": "Damage Magicka Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Harvested from the blue variety of Mountain Flower, found throughout Skyrim."
   },
   {
    "idx": 14,
    "nam": "Boar Tusk",
    "val": "20",
    "wgt": "0.5",
    "plt": "",
    "dlc": "DB",
    "eff": [
     {
      "idx": 26,
      "nam": "Fortify Stamina",
      "val": "1.25",
      "mag": "5.9",
      "lix": true
     },
     {
      "idx": 14,
      "nam": "Fortify Health",
      "val": "5.9",
      "mag": 1,
      "lix": true
     },
     {
      "idx": 9,
      "nam": "Fortify Block",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 28,
      "nam": "Frenzy",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Collected from dead bristlebacks and rieklings."
   },
   {
    "idx": 15,
    "nam": "Bone Meal",
    "val": "5",
    "wgt": "0.5",
    "plt": "Common",
    "dlc": "none",
    "eff": [
     {
      "idx": 5,
      "nam": "Damage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 40,
      "nam": "Resist Fire",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 11,
      "nam": "Fortify Conjuration",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 36,
      "nam": "Ravage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Collected from undead such as skeletons, and Draugr."
   },
   {
    "idx": 16,
    "nam": "Briar Heart",
    "val": "20",
    "wgt": "0.5",
    "plt": "Rare",
    "dlc": "none",
    "eff": [
     {
      "idx": 46,
      "nam": "Restore Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 9,
      "nam": "Fortify Block",
      "val": 1,
      "mag": "0.5",
      "lix": true
     },
     {
      "idx": 33,
      "nam": "Paralysis",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 19,
      "nam": "Fortify Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from Forsworn Briarhearts."
   },
   {
    "idx": 17,
    "nam": "Burnt Spriggan Wood",
    "val": "20",
    "wgt": "0.5",
    "plt": "",
    "dlc": "DB",
    "eff": [
     {
      "idx": 50,
      "nam": "Weakness to Fire",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 7,
      "nam": "Fortify Alteration",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 2,
      "nam": "Damage Magicka Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 48,
      "nam": "Slow",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Collected from dead burnt spriggans."
   },
   {
    "idx": 18,
    "nam": "Butterfly Wing",
    "val": "3",
    "wgt": "0.1",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 45,
      "nam": "Restore Health",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 8,
      "nam": "Fortify Barter",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 32,
      "nam": "Lingering Damage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 3,
      "nam": "Damage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Collected from catching Monarch Butterflies. Often found during daylight hours near flowering plants."
   },
   {
    "idx": 19,
    "nam": "Canis Root",
    "val": "5",
    "wgt": "0.1",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 5,
      "nam": "Damage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 21,
      "nam": "Fortify One-handed",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 20,
      "nam": "Fortify Marksman",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 33,
      "nam": "Paralysis",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Harvested from Canis Root, found in The Rift and Hjaalmarch."
   },
   {
    "idx": 20,
    "nam": "Charred Skeever Hide",
    "val": "1",
    "wgt": "0.5",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 47,
      "nam": "Restore Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 0,
      "nam": "Cure Disease",
      "val": "0.36",
      "mag": 1,
      "lix": true
     },
     {
      "idx": 43,
      "nam": "Resist Poison",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 45,
      "nam": "Restore Health",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Food, collected from dead Skeevers found on roasting spits."
   },
   {
    "idx": 21,
    "nam": "Chaurus Eggs",
    "val": "10",
    "wgt": "0.2",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 53,
      "nam": "Weakness to Poison",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 26,
      "nam": "Fortify Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 3,
      "nam": "Damage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 29,
      "nam": "Invisibility",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from Chaurus Egg Sacs, found in Falmer caves."
   },
   {
    "idx": 22,
    "nam": "Chaurus Hunter Antennae",
    "val": "2",
    "wgt": "0.1",
    "plt": "None",
    "dlc": "DG",
    "eff": [
     {
      "idx": 5,
      "nam": "Damage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 11,
      "nam": "Fortify Conjuration",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 2,
      "nam": "Damage Magicka Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 13,
      "nam": "Fortify Enchanting",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from dead Chaurus Hunters and Chaurus Hunter Fledglings."
   },
   {
    "idx": 23,
    "nam": "Chicken's Egg",
    "val": "2",
    "wgt": "0.5",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 42,
      "nam": "Resist Magic",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 2,
      "nam": "Damage Magicka Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 49,
      "nam": "Waterbreathing",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 32,
      "nam": "Lingering Damage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Food, harvested from Chicken nests in various farms."
   },
   {
    "idx": 24,
    "nam": "Creep Cluster",
    "val": "1",
    "wgt": "0.2",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 46,
      "nam": "Restore Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 4,
      "nam": "Damage Stamina Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 10,
      "nam": "Fortify Carry Weight",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 52,
      "nam": "Weakness to Magic",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Harvested from Creep Cluster, found in the volcanic tundra of Eastmarch."
   },
   {
    "idx": 25,
    "nam": "Crimson Nirnroot",
    "val": "10",
    "wgt": "0.2",
    "plt": "None",
    "dlc": "none",
    "eff": [
     {
      "idx": 1,
      "nam": "Damage Health",
      "val": 1,
      "mag": "3",
      "lix": false
     },
     {
      "idx": 5,
      "nam": "Damage Stamina",
      "val": 1,
      "mag": "3",
      "lix": false
     },
     {
      "idx": 29,
      "nam": "Invisibility",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 42,
      "nam": "Resist Magic",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from Crimson Nirnroot, found in Blackreach, needed for the quest A Return To Your Roots."
   },
   {
    "idx": 26,
    "nam": "Cyrodilic Spadetail",
    "val": "15",
    "wgt": "0.25",
    "plt": "Common",
    "dlc": "none",
    "eff": [
     {
      "idx": 5,
      "nam": "Damage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 23,
      "nam": "Fortify Restoration",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 6,
      "nam": "Fear",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 34,
      "nam": "Ravage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Collected by catching Cyrodilic Spadetail fish."
   },
   {
    "idx": 27,
    "nam": "Daedra Heart",
    "val": "250",
    "wgt": "0.5",
    "plt": "Rare",
    "dlc": "none",
    "eff": [
     {
      "idx": 45,
      "nam": "Restore Health",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 4,
      "nam": "Damage Stamina Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 3,
      "nam": "Damage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 6,
      "nam": "Fear",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Collected from dead Dremora."
   },
   {
    "idx": 28,
    "nam": "Deathbell",
    "val": "4",
    "wgt": "0.1",
    "plt": "Rare",
    "dlc": "none",
    "eff": [
     {
      "idx": 1,
      "nam": "Damage Health",
      "val": 1,
      "mag": "1.5",
      "lix": false
     },
     {
      "idx": 36,
      "nam": "Ravage Stamina",
      "val": "2.1",
      "mag": 1,
      "lix": false
     },
     {
      "idx": 48,
      "nam": "Slow",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 53,
      "nam": "Weakness to Poison",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Harvested from Deathbell, found in Hjaalmarch."
   },
   {
    "idx": 29,
    "nam": "Dragon's Tongue",
    "val": "5",
    "wgt": "0.1",
    "plt": "Common",
    "dlc": "none",
    "eff": [
     {
      "idx": 40,
      "nam": "Resist Fire",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 8,
      "nam": "Fortify Barter",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 16,
      "nam": "Fortify Illusion",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 27,
      "nam": "Fortify Two-handed",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from Dragon's Tongue, found in the volcanic tundra of Eastmarch."
   },
   {
    "idx": 30,
    "nam": "Dwarven Oil",
    "val": "15",
    "wgt": "0.25",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 52,
      "nam": "Weakness to Magic",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 16,
      "nam": "Fortify Illusion",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 38,
      "nam": "Regenerate Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 46,
      "nam": "Restore Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from destroyed Dwarven Automatons, found in Dwarven Ruins."
   },
   {
    "idx": 31,
    "nam": "Ectoplasm",
    "val": "25",
    "wgt": "0.1",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 46,
      "nam": "Restore Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 12,
      "nam": "Fortify Destruction",
      "val": 1,
      "mag": "0.8",
      "lix": true
     },
     {
      "idx": 19,
      "nam": "Fortify Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 1,
      "nam": "Damage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Collected from undead Ghosts."
   },
   {
    "idx": 32,
    "nam": "Elves Ear",
    "val": "10",
    "wgt": "0.1",
    "plt": "Common",
    "dlc": "none",
    "eff": [
     {
      "idx": 46,
      "nam": "Restore Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 20,
      "nam": "Fortify Marksman",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 51,
      "nam": "Weakness to Frost",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 40,
      "nam": "Resist Fire",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from Dried Elves Ear bunches found in homes and camps."
   },
   {
    "idx": 33,
    "nam": "Emperor Parasol Moss",
    "val": "1",
    "wgt": "0.25",
    "plt": "",
    "dlc": "DB",
    "eff": [
     {
      "idx": 1,
      "nam": "Damage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 19,
      "nam": "Fortify Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 37,
      "nam": "Regenerate Health",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 27,
      "nam": "Fortify Two-handed",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from emperor parasol moss plants near Tel Mithryn."
   },
   {
    "idx": 34,
    "nam": "Eye of Sabre Cat",
    "val": "2",
    "wgt": "0.1",
    "plt": "None (Uncommon)",
    "dlc": "none",
    "eff": [
     {
      "idx": 47,
      "nam": "Restore Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 34,
      "nam": "Ravage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 3,
      "nam": "Damage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 45,
      "nam": "Restore Health",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from dead Sabre Cats."
   },
   {
    "idx": 35,
    "nam": "Falmer Ear",
    "val": "10",
    "wgt": "0.2",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 1,
      "nam": "Damage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 28,
      "nam": "Frenzy",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 43,
      "nam": "Resist Poison",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 18,
      "nam": "Fortify Lockpicking",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from dead Falmer."
   },
   {
    "idx": 36,
    "nam": "Farengar's Frost Salt",
    "val": "100",
    "wgt": "0.25",
    "plt": "None",
    "dlc": "none",
    "eff": [
     {
      "idx": 50,
      "nam": "Weakness to Fire",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 41,
      "nam": "Resist Frost",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 46,
      "nam": "Restore Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 11,
      "nam": "Fortify Conjuration",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "This ingredient is given as a quest item. It is identical to standard Frost Salts, except for its name."
   },
   {
    "idx": 37,
    "nam": "Felsaad Tern Feathers",
    "val": "15",
    "wgt": "0.1",
    "plt": "",
    "dlc": "DB",
    "eff": [
     {
      "idx": 45,
      "nam": "Restore Health",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 17,
      "nam": "Fortify Light Armor",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 0,
      "nam": "Cure Disease",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 42,
      "nam": "Resist Magic",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from dead Felsaad terns."
   },
   {
    "idx": 38,
    "nam": "Fine-Cut Void Salts",
    "val": "125",
    "wgt": "0.2",
    "plt": "None",
    "dlc": "none",
    "eff": [
     {
      "idx": 54,
      "nam": "Weakness to Shock",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 42,
      "nam": "Resist Magic",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 1,
      "nam": "Damage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 19,
      "nam": "Fortify Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "This ingredient is given as a quest item. It is identical to standard Void Salts, except for its name."
   },
   {
    "idx": 39,
    "nam": "Fire Salts",
    "val": "50",
    "wgt": "0.25",
    "plt": "Rare",
    "dlc": "none",
    "eff": [
     {
      "idx": 51,
      "nam": "Weakness to Frost",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 40,
      "nam": "Resist Fire",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 46,
      "nam": "Restore Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 38,
      "nam": "Regenerate Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from dead Flame Atronachs, a type of daedra."
   },
   {
    "idx": 40,
    "nam": "Fly Amanita",
    "val": "2",
    "wgt": "0.1",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 40,
      "nam": "Resist Fire",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 27,
      "nam": "Fortify Two-handed",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 28,
      "nam": "Frenzy",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 39,
      "nam": "Regenerate Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from Fly Amanita mushrooms, found in various caves."
   },
   {
    "idx": 41,
    "nam": "Frost Mirriam",
    "val": "1",
    "wgt": "0.1",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 41,
      "nam": "Resist Frost",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 25,
      "nam": "Fortify Sneak",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 35,
      "nam": "Ravage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 4,
      "nam": "Damage Stamina Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Harvested from Dried Frost Mirriam bunches found in homes and camps."
   },
   {
    "idx": 42,
    "nam": "Frost Salts",
    "val": "100",
    "wgt": "0.25",
    "plt": "Rare",
    "dlc": "none",
    "eff": [
     {
      "idx": 50,
      "nam": "Weakness to Fire",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 41,
      "nam": "Resist Frost",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 46,
      "nam": "Restore Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 11,
      "nam": "Fortify Conjuration",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from dead Frost Atronachs, a type of daedra."
   },
   {
    "idx": 43,
    "nam": "Garlic",
    "val": "1",
    "wgt": "0.25",
    "plt": "Common",
    "dlc": "none",
    "eff": [
     {
      "idx": 43,
      "nam": "Resist Poison",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 26,
      "nam": "Fortify Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 38,
      "nam": "Regenerate Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 37,
      "nam": "Regenerate Health",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Food. Can also be harvested from Garlic Braids."
   },
   {
    "idx": 44,
    "nam": "Giant's Toe",
    "val": "20",
    "wgt": "1",
    "plt": "Rare",
    "dlc": "none",
    "eff": [
     {
      "idx": 5,
      "nam": "Damage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 14,
      "nam": "Fortify Health",
      "val": "5.9",
      "mag": 1,
      "lix": true
     },
     {
      "idx": 10,
      "nam": "Fortify Carry Weight",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 4,
      "nam": "Damage Stamina Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Collected from dead Giants, which can be found in Giant Camps."
   },
   {
    "idx": 45,
    "nam": "Giant Lichen",
    "val": "5",
    "wgt": "0.25",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 54,
      "nam": "Weakness to Shock",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 34,
      "nam": "Ravage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 53,
      "nam": "Weakness to Poison",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 46,
      "nam": "Restore Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from Giant Lichen, found in Hjaalmarch."
   },
   {
    "idx": 46,
    "nam": "Gleamblossom",
    "val": "5",
    "wgt": "0.1",
    "plt": "None",
    "dlc": "DG",
    "eff": [
     {
      "idx": 42,
      "nam": "Resist Magic",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 6,
      "nam": "Fear",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 37,
      "nam": "Regenerate Health",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 33,
      "nam": "Paralysis",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Harvested from the plant of the same name."
   },
   {
    "idx": 47,
    "nam": "Glow Dust",
    "val": "20",
    "wgt": "0.5",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 3,
      "nam": "Damage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 2,
      "nam": "Damage Magicka Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 12,
      "nam": "Fortify Destruction",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 44,
      "nam": "Resist Shock",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from dead Wisps and Wispmothers."
   },
   {
    "idx": 48,
    "nam": "Glowing Mushroom",
    "val": "5",
    "wgt": "0.2",
    "plt": "None",
    "dlc": "none",
    "eff": [
     {
      "idx": 44,
      "nam": "Resist Shock",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 12,
      "nam": "Fortify Destruction",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 24,
      "nam": "Fortify Smithing",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 14,
      "nam": "Fortify Health",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from Glowing Mushrooms, found in various caves."
   },
   {
    "idx": 49,
    "nam": "Grass Pod",
    "val": "1",
    "wgt": "0.1",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 43,
      "nam": "Resist Poison",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 35,
      "nam": "Ravage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 7,
      "nam": "Fortify Alteration",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 46,
      "nam": "Restore Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from Spiky Grass, found in northern regions of Skyrim."
   },
   {
    "idx": 50,
    "nam": "Hagraven Claw",
    "val": "20",
    "wgt": "0.25",
    "plt": "Rare",
    "dlc": "none",
    "eff": [
     {
      "idx": 42,
      "nam": "Resist Magic",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 31,
      "nam": "Lingering Damage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 13,
      "nam": "Fortify Enchanting",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 8,
      "nam": "Fortify Barter",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from dead Hagravens."
   },
   {
    "idx": 51,
    "nam": "Hagraven Feathers",
    "val": "20",
    "wgt": "0.1",
    "plt": "Rare",
    "dlc": "none",
    "eff": [
     {
      "idx": 3,
      "nam": "Damage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 11,
      "nam": "Fortify Conjuration",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 28,
      "nam": "Frenzy",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 54,
      "nam": "Weakness to Shock",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Collected from dead Hagravens. Can also be found scattered around their sleeping areas."
   },
   {
    "idx": 52,
    "nam": "Hanging Moss",
    "val": "1",
    "wgt": "0.25",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 3,
      "nam": "Damage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 14,
      "nam": "Fortify Health",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 2,
      "nam": "Damage Magicka Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 21,
      "nam": "Fortify One-handed",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from Hanging Moss."
   },
   {
    "idx": 53,
    "nam": "Hawk's Egg",
    "val": "5",
    "wgt": "0.5",
    "plt": "None",
    "dlc": "HF",
    "eff": [
     {
      "idx": 42,
      "nam": "Resist Magic",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 2,
      "nam": "Damage Magicka Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 49,
      "nam": "Waterbreathing",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 32,
      "nam": "Lingering Damage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Harvested from Hawk nests."
   },
   {
    "idx": 54,
    "nam": "Hawk Beak",
    "val": "15",
    "wgt": "0.25",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 47,
      "nam": "Restore Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 41,
      "nam": "Resist Frost",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 10,
      "nam": "Fortify Carry Weight",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 44,
      "nam": "Resist Shock",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from dead Hawks."
   },
   {
    "idx": 55,
    "nam": "Hawk Feathers",
    "val": "15",
    "wgt": "0.1",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 0,
      "nam": "Cure Disease",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 17,
      "nam": "Fortify Light Armor",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 21,
      "nam": "Fortify One-handed",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 25,
      "nam": "Fortify Sneak",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from dead Hawks."
   },
   {
    "idx": 56,
    "nam": "Histcarp",
    "val": "6",
    "wgt": "0.25",
    "plt": "Common",
    "dlc": "none",
    "eff": [
     {
      "idx": 47,
      "nam": "Restore Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 19,
      "nam": "Fortify Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 4,
      "nam": "Damage Stamina Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 49,
      "nam": "Waterbreathing",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected by catching Histcarp fish."
   },
   {
    "idx": 57,
    "nam": "Honeycomb",
    "val": "5",
    "wgt": "1",
    "plt": "None (Common)",
    "dlc": "none",
    "eff": [
     {
      "idx": 47,
      "nam": "Restore Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 9,
      "nam": "Fortify Block",
      "val": 1,
      "mag": "0.5",
      "lix": true
     },
     {
      "idx": 17,
      "nam": "Fortify Light Armor",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 36,
      "nam": "Ravage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Food. Collected from beehives."
   },
   {
    "idx": 58,
    "nam": "Human Flesh",
    "val": "1",
    "wgt": "0.25",
    "plt": "None",
    "dlc": "none",
    "eff": [
     {
      "idx": 1,
      "nam": "Damage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 33,
      "nam": "Paralysis",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 46,
      "nam": "Restore Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 25,
      "nam": "Fortify Sneak",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Cannot be harvested or collected; with the Dawnguard plug-in installed, several respawning samples can be found in Volkihar Keep."
   },
   {
    "idx": 59,
    "nam": "Human Heart",
    "val": "0",
    "wgt": "1",
    "plt": "None",
    "dlc": "none",
    "eff": [
     {
      "idx": 1,
      "nam": "Damage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 3,
      "nam": "Damage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 2,
      "nam": "Damage Magicka Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 28,
      "nam": "Frenzy",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Cannot be harvested or collected; limited number of samples available."
   },
   {
    "idx": 60,
    "nam": "Ice Wraith Teeth",
    "val": "30",
    "wgt": "0.25",
    "plt": "Rare",
    "dlc": "none",
    "eff": [
     {
      "idx": 51,
      "nam": "Weakness to Frost",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 15,
      "nam": "Fortify Heavy Armor",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 29,
      "nam": "Invisibility",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 50,
      "nam": "Weakness to Fire",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Collected from Ice Wraiths."
   },
   {
    "idx": 61,
    "nam": "Imp Stool",
    "val": "0",
    "wgt": "0.3",
    "plt": "Rare",
    "dlc": "none",
    "eff": [
     {
      "idx": 1,
      "nam": "Damage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 30,
      "nam": "Lingering Damage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 33,
      "nam": "Paralysis",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 45,
      "nam": "Restore Health",
      "val": 1,
      "mag": "0.6",
      "lix": true
     }
    ],
    "src": "Harvested from Imp Stool mushrooms, found in various caves."
   },
   {
    "idx": 62,
    "nam": "Jarrin Root",
    "val": "10",
    "wgt": "0.5",
    "plt": "None",
    "dlc": "none",
    "eff": [
     {
      "idx": 1,
      "nam": "Damage Health",
      "val": 1,
      "mag": "100",
      "lix": false
     },
     {
      "idx": 3,
      "nam": "Damage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 5,
      "nam": "Damage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 2,
      "nam": "Damage Magicka Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "You may only receive this ingredient once during the Dark Brotherhood quest line."
   },
   {
    "idx": 63,
    "nam": "Jazbay Grapes",
    "val": "1",
    "wgt": "0.2",
    "plt": "Rare",
    "dlc": "none",
    "eff": [
     {
      "idx": 52,
      "nam": "Weakness to Magic",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 19,
      "nam": "Fortify Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 38,
      "nam": "Regenerate Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 34,
      "nam": "Ravage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Harvested from Jazbay vines, found in the volcanic tundra of Eastmarch."
   },
   {
    "idx": 64,
    "nam": "Juniper Berries",
    "val": "1",
    "wgt": "0.1",
    "plt": "Common",
    "dlc": "none",
    "eff": [
     {
      "idx": 50,
      "nam": "Weakness to Fire",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 20,
      "nam": "Fortify Marksman",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 37,
      "nam": "Regenerate Health",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 4,
      "nam": "Damage Stamina Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Harvested from Juniper shrubs, common in The Reach."
   },
   {
    "idx": 65,
    "nam": "Large Antlers",
    "val": "2",
    "wgt": "0.1",
    "plt": "None (Uncommon)",
    "dlc": "none",
    "eff": [
     {
      "idx": 47,
      "nam": "Restore Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 26,
      "nam": "Fortify Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 48,
      "nam": "Slow",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 4,
      "nam": "Damage Stamina Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Collected from dead male Elk."
   },
   {
    "idx": 66,
    "nam": "Lavender",
    "val": "1",
    "wgt": "0.1",
    "plt": "Common",
    "dlc": "none",
    "eff": [
     {
      "idx": 42,
      "nam": "Resist Magic",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 26,
      "nam": "Fortify Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 35,
      "nam": "Ravage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 11,
      "nam": "Fortify Conjuration",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from Lavender, most common in Whiterun Hold."
   },
   {
    "idx": 67,
    "nam": "Luna Moth Wing",
    "val": "5",
    "wgt": "0.1",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 3,
      "nam": "Damage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 17,
      "nam": "Fortify Light Armor",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 37,
      "nam": "Regenerate Health",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 29,
      "nam": "Invisibility",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected by catching Luna Moths. Often found near flowers after dark."
   },
   {
    "idx": 68,
    "nam": "Moon Sugar",
    "val": "50",
    "wgt": "0.25",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 50,
      "nam": "Weakness to Fire",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 41,
      "nam": "Resist Frost",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 46,
      "nam": "Restore Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 38,
      "nam": "Regenerate Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Cannot be collected or harvested. Can be purchased from the Khajiit Traders."
   },
   {
    "idx": 69,
    "nam": "Mora Tapinella",
    "val": "4",
    "wgt": "0.25",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 46,
      "nam": "Restore Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 30,
      "nam": "Lingering Damage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 39,
      "nam": "Regenerate Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 16,
      "nam": "Fortify Illusion",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from Mora Tapinella mushrooms, found growing on dead trees."
   },
   {
    "idx": 70,
    "nam": "Mudcrab Chitin",
    "val": "2",
    "wgt": "0.25",
    "plt": "None (Common)",
    "dlc": "none",
    "eff": [
     {
      "idx": 47,
      "nam": "Restore Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 0,
      "nam": "Cure Disease",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 43,
      "nam": "Resist Poison",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 40,
      "nam": "Resist Fire",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from dead Mudcrabs, found in or near bodies of water."
   },
   {
    "idx": 71,
    "nam": "Namira's Rot",
    "val": "0",
    "wgt": "0.25",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 3,
      "nam": "Damage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 18,
      "nam": "Fortify Lockpicking",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 6,
      "nam": "Fear",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 37,
      "nam": "Regenerate Health",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from Namira's Rot mushrooms, found in various caves."
   },
   {
    "idx": 72,
    "nam": "Netch Jelly",
    "val": "20",
    "wgt": "0.5",
    "plt": "",
    "dlc": "DB",
    "eff": [
     {
      "idx": 33,
      "nam": "Paralysis",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 10,
      "nam": "Fortify Carry Weight",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 47,
      "nam": "Restore Stamina",
      "val": 1,
      "mag": "2",
      "lix": true
     },
     {
      "idx": 6,
      "nam": "Fear",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Collected from dead netch."
   },
   {
    "idx": 73,
    "nam": "Nightshade",
    "val": "8",
    "wgt": "0.1",
    "plt": "Rare",
    "dlc": "none",
    "eff": [
     {
      "idx": 1,
      "nam": "Damage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 2,
      "nam": "Damage Magicka Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 32,
      "nam": "Lingering Damage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 12,
      "nam": "Fortify Destruction",
      "val": 1,
      "mag": "0.8",
      "lix": true
     }
    ],
    "src": "Harvested from Nightshade, found growing throughout Skyrim."
   },
   {
    "idx": 74,
    "nam": "Nirnroot",
    "val": "10",
    "wgt": "0.2",
    "plt": "Rare",
    "dlc": "none",
    "eff": [
     {
      "idx": 1,
      "nam": "Damage Health",
      "val": "12.6",
      "mag": 1,
      "lix": false
     },
     {
      "idx": 5,
      "nam": "Damage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 29,
      "nam": "Invisibility",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 42,
      "nam": "Resist Magic",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from Nirnroot, found near bodies of water throughout Skyrim."
   },
   {
    "idx": 75,
    "nam": "Nordic Barnacle",
    "val": "5",
    "wgt": "0.2",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 3,
      "nam": "Damage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 49,
      "nam": "Waterbreathing",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 37,
      "nam": "Regenerate Health",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 22,
      "nam": "Fortify Pickpocket",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from Nordic Barnacle Clusters, found in or near water."
   },
   {
    "idx": 76,
    "nam": "Orange Dartwing",
    "val": "1",
    "wgt": "0.1",
    "plt": "None (Common)",
    "dlc": "none",
    "eff": [
     {
      "idx": 47,
      "nam": "Restore Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 35,
      "nam": "Ravage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 22,
      "nam": "Fortify Pickpocket",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 30,
      "nam": "Lingering Damage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Collected by catching Dragonflies found near rivers and streams below the snow line."
   },
   {
    "idx": 77,
    "nam": "Pearl",
    "val": "2",
    "wgt": "0.1",
    "plt": "None (Uncommon)",
    "dlc": "none",
    "eff": [
     {
      "idx": 47,
      "nam": "Restore Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 9,
      "nam": "Fortify Block",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 46,
      "nam": "Restore Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 44,
      "nam": "Resist Shock",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Cannot be harvested or collected in the original version of the game; only readily available after the Merchant perk has been unlocked. With Dragonborn, they can be harvested from Pearl Oysters in Solstheim."
   },
   {
    "idx": 78,
    "nam": "Pine Thrush Egg",
    "val": "2",
    "wgt": "0.5",
    "plt": "Common",
    "dlc": "none",
    "eff": [
     {
      "idx": 47,
      "nam": "Restore Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 18,
      "nam": "Fortify Lockpicking",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 53,
      "nam": "Weakness to Poison",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 44,
      "nam": "Resist Shock",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from bird nests in forested regions, in particular The Rift."
   },
   {
    "idx": 79,
    "nam": "Poison Bloom",
    "val": "5",
    "wgt": "0.25",
    "plt": "None",
    "dlc": "DG",
    "eff": [
     {
      "idx": 1,
      "nam": "Damage Health",
      "val": 1,
      "mag": "1.5",
      "lix": false
     },
     {
      "idx": 48,
      "nam": "Slow",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 10,
      "nam": "Fortify Carry Weight",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 6,
      "nam": "Fear",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Harvested from the plant of the same name."
   },
   {
    "idx": 80,
    "nam": "Powdered Mammoth Tusk",
    "val": "2",
    "wgt": "0.1",
    "plt": "None (Uncommon)",
    "dlc": "none",
    "eff": [
     {
      "idx": 47,
      "nam": "Restore Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 25,
      "nam": "Fortify Sneak",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 50,
      "nam": "Weakness to Fire",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 6,
      "nam": "Fear",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Cannot be harvested or collected; only readily available after the Merchant perk has been unlocked."
   },
   {
    "idx": 81,
    "nam": "Purple Mountain Flower",
    "val": "2",
    "wgt": "0.1",
    "plt": "Common",
    "dlc": "none",
    "eff": [
     {
      "idx": 47,
      "nam": "Restore Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 25,
      "nam": "Fortify Sneak",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 31,
      "nam": "Lingering Damage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 41,
      "nam": "Resist Frost",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from the purple variety of Mountain Flower."
   },
   {
    "idx": 82,
    "nam": "Red Mountain Flower",
    "val": "2",
    "wgt": "0.1",
    "plt": "Common",
    "dlc": "none",
    "eff": [
     {
      "idx": 46,
      "nam": "Restore Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 35,
      "nam": "Ravage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 19,
      "nam": "Fortify Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 1,
      "nam": "Damage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Harvested from the red variety of Mountain Flower."
   },
   {
    "idx": 83,
    "nam": "River Betty",
    "val": "15",
    "wgt": "0.25",
    "plt": "Common",
    "dlc": "none",
    "eff": [
     {
      "idx": 1,
      "nam": "Damage Health",
      "val": 1,
      "mag": "2.5",
      "lix": false
     },
     {
      "idx": 7,
      "nam": "Fortify Alteration",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 48,
      "nam": "Slow",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 10,
      "nam": "Fortify Carry Weight",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected by catching River Betty fish."
   },
   {
    "idx": 84,
    "nam": "Rock Warbler Egg",
    "val": "2",
    "wgt": "0.5",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 45,
      "nam": "Restore Health",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 21,
      "nam": "Fortify One-handed",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 5,
      "nam": "Damage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 52,
      "nam": "Weakness to Magic",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Harvested from bird nests in rocky regions, in particular The Reach."
   },
   {
    "idx": 85,
    "nam": "Sabre Cat Tooth",
    "val": "2",
    "wgt": "0.1",
    "plt": "None (Uncommon)",
    "dlc": "none",
    "eff": [
     {
      "idx": 47,
      "nam": "Restore Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 15,
      "nam": "Fortify Heavy Armor",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 24,
      "nam": "Fortify Smithing",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 53,
      "nam": "Weakness to Poison",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Collected from dead Sabre cats."
   },
   {
    "idx": 86,
    "nam": "Salmon Roe",
    "val": "5",
    "wgt": "0.2",
    "plt": "None",
    "dlc": "HF",
    "eff": [
     {
      "idx": 47,
      "nam": "Restore Stamina",
      "val": 1,
      "mag": "0.4",
      "lix": true
     },
     {
      "idx": 49,
      "nam": "Waterbreathing",
      "val": "15.4",
      "mag": 1,
      "lix": true
     },
     {
      "idx": 19,
      "nam": "Fortify Magicka",
      "val": "12.5",
      "mag": "1.05",
      "lix": true
     },
     {
      "idx": 38,
      "nam": "Regenerate Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from jumping Salmon."
   },
   {
    "idx": 87,
    "nam": "Salt Pile",
    "val": "2",
    "wgt": "0.2",
    "plt": "Common",
    "dlc": "none",
    "eff": [
     {
      "idx": 52,
      "nam": "Weakness to Magic",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 23,
      "nam": "Fortify Restoration",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 48,
      "nam": "Slow",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 38,
      "nam": "Regenerate Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Food. Cannot be harvested or collected, but is commonly found in barrels and sacks."
   },
   {
    "idx": 88,
    "nam": "Scaly Pholiota",
    "val": "4",
    "wgt": "0.25",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 52,
      "nam": "Weakness to Magic",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 16,
      "nam": "Fortify Illusion",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 39,
      "nam": "Regenerate Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 10,
      "nam": "Fortify Carry Weight",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from Scaly Pholiota mushrooms, found growing on dead trees."
   },
   {
    "idx": 89,
    "nam": "Scathecraw",
    "val": "1",
    "wgt": "0.1",
    "plt": "",
    "dlc": "DB",
    "eff": [
     {
      "idx": 34,
      "nam": "Ravage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 36,
      "nam": "Ravage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 35,
      "nam": "Ravage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 30,
      "nam": "Lingering Damage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Harvested from scathecraw plants."
   },
   {
    "idx": 90,
    "nam": "Silverside Perch",
    "val": "15",
    "wgt": "0.25",
    "plt": "Common",
    "dlc": "none",
    "eff": [
     {
      "idx": 47,
      "nam": "Restore Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 4,
      "nam": "Damage Stamina Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 34,
      "nam": "Ravage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 41,
      "nam": "Resist Frost",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected by catching Silverside Perch fish."
   },
   {
    "idx": 91,
    "nam": "Skeever Tail",
    "val": "3",
    "wgt": "0.2",
    "plt": "Common",
    "dlc": "none",
    "eff": [
     {
      "idx": 4,
      "nam": "Damage Stamina Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 34,
      "nam": "Ravage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 1,
      "nam": "Damage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 17,
      "nam": "Fortify Light Armor",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from dead Skeevers."
   },
   {
    "idx": 92,
    "nam": "Slaughterfish Egg",
    "val": "3",
    "wgt": "0.2",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 43,
      "nam": "Resist Poison",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 22,
      "nam": "Fortify Pickpocket",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 30,
      "nam": "Lingering Damage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 26,
      "nam": "Fortify Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from Slaughterfish Egg Nests, found in or near water."
   },
   {
    "idx": 93,
    "nam": "Slaughterfish Scales",
    "val": "3",
    "wgt": "0.1",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 41,
      "nam": "Resist Frost",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 30,
      "nam": "Lingering Damage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 15,
      "nam": "Fortify Heavy Armor",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 9,
      "nam": "Fortify Block",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from dead Slaughterfish."
   },
   {
    "idx": 94,
    "nam": "Small Antlers",
    "val": "2",
    "wgt": "0.1",
    "plt": "None (Common)",
    "dlc": "none",
    "eff": [
     {
      "idx": 53,
      "nam": "Weakness to Poison",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 23,
      "nam": "Fortify Restoration",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 32,
      "nam": "Lingering Damage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 1,
      "nam": "Damage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Collected from dead female Elk."
   },
   {
    "idx": 95,
    "nam": "Small Pearl",
    "val": "2",
    "wgt": "0.1",
    "plt": "None (Uncommon)",
    "dlc": "none",
    "eff": [
     {
      "idx": 47,
      "nam": "Restore Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 21,
      "nam": "Fortify One-handed",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 23,
      "nam": "Fortify Restoration",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 41,
      "nam": "Resist Frost",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Cannot be harvested or collected in the original version of the game; only readily available after the Merchant perk has been unlocked. With Dragonborn, they can be harvested from Pearl Oysters in Solstheim."
   },
   {
    "idx": 96,
    "nam": "Snowberries",
    "val": "4",
    "wgt": "0.1",
    "plt": "Common",
    "dlc": "none",
    "eff": [
     {
      "idx": 40,
      "nam": "Resist Fire",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 13,
      "nam": "Fortify Enchanting",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 41,
      "nam": "Resist Frost",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 44,
      "nam": "Resist Shock",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from Snowberry bushes, found in snowy regions of Skyrim."
   },
   {
    "idx": 97,
    "nam": "Spawn Ash",
    "val": "20",
    "wgt": "0.1",
    "plt": "",
    "dlc": "DB",
    "eff": [
     {
      "idx": 36,
      "nam": "Ravage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 40,
      "nam": "Resist Fire",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 13,
      "nam": "Fortify Enchanting",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 35,
      "nam": "Ravage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Collected from dead ash spawn."
   },
   {
    "idx": 98,
    "nam": "Spider Egg",
    "val": "5",
    "wgt": "0.2",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 5,
      "nam": "Damage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 2,
      "nam": "Damage Magicka Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 18,
      "nam": "Fortify Lockpicking",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 20,
      "nam": "Fortify Marksman",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from spider Egg Sacs and Web Sacs."
   },
   {
    "idx": 99,
    "nam": "Spriggan Sap",
    "val": "15",
    "wgt": "0.2",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 2,
      "nam": "Damage Magicka Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 13,
      "nam": "Fortify Enchanting",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 24,
      "nam": "Fortify Smithing",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 7,
      "nam": "Fortify Alteration",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Cannot be harvested or collected; best source is merchants."
   },
   {
    "idx": 100,
    "nam": "Swamp Fungal Pod",
    "val": "5",
    "wgt": "0.25",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 44,
      "nam": "Resist Shock",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 31,
      "nam": "Lingering Damage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 33,
      "nam": "Paralysis",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 45,
      "nam": "Restore Health",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from Swamp Fungal Pod, common in the tundra marsh of Hjaalmarch."
   },
   {
    "idx": 101,
    "nam": "Taproot",
    "val": "15",
    "wgt": "0.5",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 52,
      "nam": "Weakness to Magic",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 16,
      "nam": "Fortify Illusion",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 38,
      "nam": "Regenerate Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 46,
      "nam": "Restore Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from dead Spriggans."
   },
   {
    "idx": 102,
    "nam": "Thistle Branch",
    "val": "1",
    "wgt": "0.1",
    "plt": "Common",
    "dlc": "none",
    "eff": [
     {
      "idx": 41,
      "nam": "Resist Frost",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 36,
      "nam": "Ravage Stamina",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 43,
      "nam": "Resist Poison",
      "val": 1,
      "mag": "0.75",
      "lix": true
     },
     {
      "idx": 15,
      "nam": "Fortify Heavy Armor",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from Thistle."
   },
   {
    "idx": 103,
    "nam": "Torchbug Thorax",
    "val": "1",
    "wgt": "0.1",
    "plt": "None (Common)",
    "dlc": "none",
    "eff": [
     {
      "idx": 47,
      "nam": "Restore Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 31,
      "nam": "Lingering Damage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 52,
      "nam": "Weakness to Magic",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 26,
      "nam": "Fortify Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected by catching Torchbugs. Found below the snowline after dark."
   },
   {
    "idx": 104,
    "nam": "Trama Root",
    "val": "1",
    "wgt": "0.2",
    "plt": "",
    "dlc": "DB",
    "eff": [
     {
      "idx": 54,
      "nam": "Weakness to Shock",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 10,
      "nam": "Fortify Carry Weight",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 3,
      "nam": "Damage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 48,
      "nam": "Slow",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Harvested from trama root plants."
   },
   {
    "idx": 105,
    "nam": "Troll Fat",
    "val": "15",
    "wgt": "1",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 43,
      "nam": "Resist Poison",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 27,
      "nam": "Fortify Two-handed",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 28,
      "nam": "Frenzy",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 1,
      "nam": "Damage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Collected from dead Trolls."
   },
   {
    "idx": 106,
    "nam": "Tundra Cotton",
    "val": "1",
    "wgt": "0.1",
    "plt": "Common",
    "dlc": "none",
    "eff": [
     {
      "idx": 42,
      "nam": "Resist Magic",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 19,
      "nam": "Fortify Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 9,
      "nam": "Fortify Block",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 8,
      "nam": "Fortify Barter",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Harvested from Tundra Cotton, found in Whiterun Hold."
   },
   {
    "idx": 107,
    "nam": "Vampire Dust",
    "val": "25",
    "wgt": "0.2",
    "plt": "Rare",
    "dlc": "none",
    "eff": [
     {
      "idx": 29,
      "nam": "Invisibility",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 46,
      "nam": "Restore Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 37,
      "nam": "Regenerate Health",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 0,
      "nam": "Cure Disease",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from dead Vampires."
   },
   {
    "idx": 108,
    "nam": "Void Salts",
    "val": "125",
    "wgt": "0.2",
    "plt": "Rare",
    "dlc": "none",
    "eff": [
     {
      "idx": 54,
      "nam": "Weakness to Shock",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 42,
      "nam": "Resist Magic",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 1,
      "nam": "Damage Health",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 19,
      "nam": "Fortify Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from dead Storm Atronachs."
   },
   {
    "idx": 109,
    "nam": "Wheat",
    "val": "5",
    "wgt": "0.1",
    "plt": "Common",
    "dlc": "none",
    "eff": [
     {
      "idx": 45,
      "nam": "Restore Health",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 14,
      "nam": "Fortify Health",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 4,
      "nam": "Damage Stamina Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 31,
      "nam": "Lingering Damage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Food. Harvested from wheat bushels, found in various farms."
   },
   {
    "idx": 110,
    "nam": "White Cap",
    "val": "0",
    "wgt": "0.3",
    "plt": "Uncommon",
    "dlc": "none",
    "eff": [
     {
      "idx": 51,
      "nam": "Weakness to Frost",
      "val": 1,
      "mag": 1,
      "lix": false
     },
     {
      "idx": 15,
      "nam": "Fortify Heavy Armor",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 46,
      "nam": "Restore Magicka",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 35,
      "nam": "Ravage Magicka",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Harvested from White Cap mushrooms, found in various caves."
   },
   {
    "idx": 111,
    "nam": "Wisp Wrappings",
    "val": "2",
    "wgt": "0.1",
    "plt": "None (Uncommon)",
    "dlc": "none",
    "eff": [
     {
      "idx": 47,
      "nam": "Restore Stamina",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 12,
      "nam": "Fortify Destruction",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 10,
      "nam": "Fortify Carry Weight",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 42,
      "nam": "Resist Magic",
      "val": 1,
      "mag": 1,
      "lix": true
     }
    ],
    "src": "Collected from dead Wispmothers."
   },
   {
    "idx": 112,
    "nam": "Yellow Mountain Flower",
    "val": "2",
    "wgt": "0.1",
    "plt": "None",
    "dlc": "DG",
    "eff": [
     {
      "idx": 43,
      "nam": "Resist Poison",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 23,
      "nam": "Fortify Restoration",
      "val": 1,
      "mag": "1.25",
      "lix": true
     },
     {
      "idx": 14,
      "nam": "Fortify Health",
      "val": 1,
      "mag": 1,
      "lix": true
     },
     {
      "idx": 4,
      "nam": "Damage Stamina Regen",
      "val": 1,
      "mag": 1,
      "lix": false
     }
    ],
    "src": "Harvested from the yellow variety of Mountain Flower."
   }
  ],
  "prevDisplay": [
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false
  ],
  "nextDisplay": [
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true
  ],
  "selected": [
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false
  ],
  "display": [
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null
  ]
 },
 "eff": {
  "num": {
   "Cure Disease": 0,
   "Damage Health": 1,
   "Damage Magicka Regen": 2,
   "Damage Magicka": 3,
   "Damage Stamina Regen": 4,
   "Damage Stamina": 5,
   "Fear": 6,
   "Fortify Alteration": 7,
   "Fortify Barter": 8,
   "Fortify Block": 9,
   "Fortify Carry Weight": 10,
   "Fortify Conjuration": 11,
   "Fortify Destruction": 12,
   "Fortify Enchanting": 13,
   "Fortify Health": 14,
   "Fortify Heavy Armor": 15,
   "Fortify Illusion": 16,
   "Fortify Light Armor": 17,
   "Fortify Lockpicking": 18,
   "Fortify Magicka": 19,
   "Fortify Marksman": 20,
   "Fortify One-handed": 21,
   "Fortify Pickpocket": 22,
   "Fortify Restoration": 23,
   "Fortify Smithing": 24,
   "Fortify Sneak": 25,
   "Fortify Stamina": 26,
   "Fortify Two-handed": 27,
   "Frenzy": 28,
   "Invisibility": 29,
   "Lingering Damage Health": 30,
   "Lingering Damage Magicka": 31,
   "Lingering Damage Stamina": 32,
   "Paralysis": 33,
   "Ravage Health": 34,
   "Ravage Magicka": 35,
   "Ravage Stamina": 36,
   "Regenerate Health": 37,
   "Regenerate Magicka": 38,
   "Regenerate Stamina": 39,
   "Resist Fire": 40,
   "Resist Frost": 41,
   "Resist Magic": 42,
   "Resist Poison": 43,
   "Resist Shock": 44,
   "Restore Health": 45,
   "Restore Magicka": 46,
   "Restore Stamina": 47,
   "Slow": 48,
   "Waterbreathing": 49,
   "Weakness to Fire": 50,
   "Weakness to Frost": 51,
   "Weakness to Magic": 52,
   "Weakness to Poison": 53,
   "Weakness to Shock": 54
  },
  "lab": [
   {
    "idx": 0,
    "nam": "Cure Disease",
    "ing": [
     14,
     44,
     59,
     92,
     108
    ]
   },
   {
    "idx": 1,
    "nam": "Damage Health",
    "ing": [
     19,
     22,
     25,
     28,
     48,
     49,
     51,
     61,
     62,
     67,
     70,
     71,
     78,
     81,
     90,
     93,
     100,
     101,
     107
    ]
   },
   {
    "idx": 2,
    "nam": "Damage Magicka Regen",
    "ing": [
     1,
     2,
     7,
     9,
     16,
     17,
     37,
     42,
     45,
     49,
     61,
     84,
     85,
     101,
     106
    ]
   },
   {
    "idx": 3,
    "nam": "Damage Magicka",
    "ing": [
     12,
     15,
     21,
     27,
     37,
     41,
     42,
     49,
     56,
     60,
     63,
     101,
     112
    ]
   },
   {
    "idx": 4,
    "nam": "Damage Stamina Regen",
    "ing": [
     18,
     21,
     31,
     35,
     46,
     53,
     54,
     77,
     78,
     94,
     97
    ]
   },
   {
    "idx": 5,
    "nam": "Damage Stamina",
    "ing": [
     1,
     6,
     7,
     10,
     13,
     16,
     19,
     20,
     35,
     62,
     72,
     84,
     98,
     101,
     102
    ]
   },
   {
    "idx": 6,
    "nam": "Fear",
    "ing": [
     8,
     20,
     21,
     36,
     60,
     67,
     68,
     109
    ]
   },
   {
    "idx": 7,
    "nam": "Fortify Alteration",
    "ing": [
     39,
     71,
     85,
     106
    ]
   },
   {
    "idx": 8,
    "nam": "Fortify Barter",
    "ing": [
     12,
     23,
     40,
     91
    ]
   },
   {
    "idx": 9,
    "nam": "Fortify Block",
    "ing": [
     5,
     11,
     47,
     65,
     80,
     91,
     105
    ]
   },
   {
    "idx": 10,
    "nam": "Fortify Carry Weight",
    "ing": [
     18,
     35,
     43,
     67,
     71,
     76,
     96,
     109,
     112
    ]
   },
   {
    "idx": 11,
    "nam": "Fortify Conjuration",
    "ing": [
     1,
     7,
     9,
     10,
     16,
     32,
     41,
     55,
     98,
     99
    ]
   },
   {
    "idx": 12,
    "nam": "Fortify Destruction",
    "ing": [
     4,
     25,
     37,
     38,
     61,
     96,
     102
    ]
   },
   {
    "idx": 13,
    "nam": "Fortify Enchanting",
    "ing": [
     1,
     7,
     16,
     40,
     83,
     85,
     111
    ]
   },
   {
    "idx": 14,
    "nam": "Fortify Health",
    "ing": [
     2,
     9,
     35,
     38,
     42,
     94,
     97,
     105
    ]
   },
   {
    "idx": 15,
    "nam": "Fortify Heavy Armor",
    "ing": [
     50,
     73,
     80,
     88,
     95
    ]
   },
   {
    "idx": 16,
    "nam": "Fortify Illusion",
    "ing": [
     23,
     24,
     58,
     76,
     87
    ]
   },
   {
    "idx": 17,
    "nam": "Fortify Light Armor",
    "ing": [
     4,
     44,
     47,
     56,
     78,
     103,
     108
    ]
   },
   {
    "idx": 18,
    "nam": "Fortify Lockpicking",
    "ing": [
     28,
     60,
     66,
     84,
     104
    ]
   },
   {
    "idx": 19,
    "nam": "Fortify Magicka",
    "ing": [
     11,
     25,
     46,
     52,
     70,
     74,
     91,
     93,
     100,
     107
    ]
   },
   {
    "idx": 20,
    "nam": "Fortify Marksman",
    "ing": [
     13,
     26,
     53,
     84
    ]
   },
   {
    "idx": 21,
    "nam": "Fortify One-handed",
    "ing": [
     2,
     13,
     42,
     44,
     72,
     82
    ]
   },
   {
    "idx": 22,
    "nam": "Fortify Pickpocket",
    "ing": [
     8,
     63,
     64,
     79
    ]
   },
   {
    "idx": 23,
    "nam": "Fortify Restoration",
    "ing": [
     0,
     20,
     75,
     81,
     82,
     97
    ]
   },
   {
    "idx": 24,
    "nam": "Fortify Smithing",
    "ing": [
     6,
     38,
     73,
     85
    ]
   },
   {
    "idx": 25,
    "nam": "Fortify Sneak",
    "ing": [
     0,
     4,
     31,
     44,
     48,
     68,
     69,
     104
    ]
   },
   {
    "idx": 26,
    "nam": "Fortify Stamina",
    "ing": [
     15,
     33,
     54,
     55,
     79,
     89,
     105
    ]
   },
   {
    "idx": 27,
    "nam": "Fortify Two-handed",
    "ing": [
     23,
     30,
     90,
     107
    ]
   },
   {
    "idx": 28,
    "nam": "Frenzy",
    "ing": [
     6,
     28,
     30,
     41,
     49,
     90,
     105
    ]
   },
   {
    "idx": 29,
    "nam": "Invisibility",
    "ing": [
     15,
     19,
     50,
     56,
     62,
     92,
     102
    ]
   },
   {
    "idx": 30,
    "nam": "Lingering Damage Health",
    "ing": [
     51,
     58,
     64,
     79,
     80,
     110
    ]
   },
   {
    "idx": 31,
    "nam": "Lingering Damage Magicka",
    "ing": [
     40,
     69,
     86,
     89,
     94
    ]
   },
   {
    "idx": 32,
    "nam": "Lingering Damage Stamina",
    "ing": [
     12,
     17,
     45,
     61,
     81
    ]
   },
   {
    "idx": 33,
    "nam": "Paralysis",
    "ing": [
     11,
     13,
     36,
     48,
     51,
     86,
     109
    ]
   },
   {
    "idx": 34,
    "nam": "Ravage Health",
    "ing": [
     20,
     27,
     34,
     52,
     77,
     78,
     110
    ]
   },
   {
    "idx": 35,
    "nam": "Ravage Magicka",
    "ing": [
     31,
     39,
     55,
     64,
     70,
     95,
     110,
     111
    ]
   },
   {
    "idx": 36,
    "nam": "Ravage Stamina",
    "ing": [
     3,
     10,
     22,
     47,
     88,
     98,
     110,
     111
    ]
   },
   {
    "idx": 37,
    "nam": "Regenerate Health",
    "ing": [
     33,
     36,
     53,
     56,
     60,
     63,
     92,
     107
    ]
   },
   {
    "idx": 38,
    "nam": "Regenerate Magicka",
    "ing": [
     24,
     29,
     33,
     52,
     57,
     74,
     75,
     87
    ]
   },
   {
    "idx": 39,
    "nam": "Regenerate Stamina",
    "ing": [
     3,
     30,
     58,
     76
    ]
   },
   {
    "idx": 40,
    "nam": "Resist Fire",
    "ing": [
     10,
     23,
     26,
     29,
     30,
     59,
     83,
     98,
     102,
     104,
     111
    ]
   },
   {
    "idx": 41,
    "nam": "Resist Frost",
    "ing": [
     31,
     32,
     43,
     57,
     69,
     77,
     80,
     82,
     83,
     88,
     99
    ]
   },
   {
    "idx": 42,
    "nam": "Resist Magic",
    "ing": [
     5,
     17,
     19,
     36,
     40,
     45,
     55,
     62,
     91,
     93,
     96,
     100,
     108
    ]
   },
   {
    "idx": 43,
    "nam": "Resist Poison",
    "ing": [
     4,
     14,
     28,
     33,
     39,
     59,
     79,
     88,
     90,
     97
    ]
   },
   {
    "idx": 44,
    "nam": "Resist Shock",
    "ing": [
     8,
     37,
     38,
     43,
     65,
     66,
     83,
     86,
     103
    ]
   },
   {
    "idx": 45,
    "nam": "Restore Health",
    "ing": [
     6,
     8,
     9,
     12,
     14,
     21,
     27,
     51,
     72,
     86,
     94,
     103,
     108
    ]
   },
   {
    "idx": 46,
    "nam": "Restore Magicka",
    "ing": [
     11,
     18,
     24,
     25,
     26,
     29,
     32,
     34,
     39,
     48,
     57,
     58,
     65,
     70,
     87,
     92,
     95,
     99
    ]
   },
   {
    "idx": 47,
    "nam": "Restore Stamina",
    "ing": [
     2,
     3,
     14,
     27,
     43,
     46,
     47,
     54,
     59,
     64,
     65,
     66,
     68,
     69,
     73,
     74,
     77,
     82,
     89,
     96,
     109
    ]
   },
   {
    "idx": 48,
    "nam": "Slow",
    "ing": [
     22,
     54,
     67,
     71,
     75,
     106,
     112
    ]
   },
   {
    "idx": 49,
    "nam": "Waterbreathing",
    "ing": [
     17,
     45,
     46,
     63,
     74
    ]
   },
   {
    "idx": 50,
    "nam": "Weakness to Fire",
    "ing": [
     5,
     32,
     50,
     53,
     57,
     68,
     99,
     106
    ]
   },
   {
    "idx": 51,
    "nam": "Weakness to Frost",
    "ing": [
     0,
     26,
     29,
     50,
     95,
     103
    ]
   },
   {
    "idx": 52,
    "nam": "Weakness to Magic",
    "ing": [
     18,
     24,
     52,
     72,
     75,
     76,
     87,
     89
    ]
   },
   {
    "idx": 53,
    "nam": "Weakness to Poison",
    "ing": [
     0,
     5,
     15,
     22,
     34,
     66,
     73,
     81
    ]
   },
   {
    "idx": 54,
    "nam": "Weakness to Shock",
    "ing": [
     3,
     34,
     41,
     93,
     100,
     104,
     112
    ]
   }
  ],
  "prevDisplay": [
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false
  ],
  "nextDisplay": [
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true
  ],
  "selected": [
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false
  ],
  "display": [
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null
  ]
 },
 "metrics": {
  "ing": {
   "dlc": {
    "none": 95,
    "DG": 5,
    "HF": 2,
    "DB": 11
   },
   "plt": {
    "Common": 22,
    "None": 15,
    "None (Uncommon)": 9,
    "None (Common)": 6,
    "Uncommon": 35,
    "Rare": 15,
    "": 11
   }
  }
 }
}
);}
