// autogenerated content -- DO NOT MODIFY
(function( spot_ns, $, undefined ) {

spot_ns.check_sum = {
 "index_base": "8DE-7E3"
};

spot_ns.index = 
{
 "i": {
  "h": {
   "Abecean Longfin": 0,
   "Ancestor Moth Wing": 1,
   "Ash Creep Cluster": 2,
   "Ash Hopper Jelly": 3,
   "Ashen Grass Pod": 4,
   "Bear Claws": 5,
   "Bee": 6,
   "Beehive Husk": 7,
   "Berit's Ashes": 8,
   "Bleeding Crown": 9,
   "Blisterwort": 10,
   "Blue Butterfly Wing": 11,
   "Blue Dartwing": 12,
   "Blue Mountain Flower": 13,
   "Boar Tusk": 14,
   "Bone Meal": 15,
   "Briar Heart": 16,
   "Burnt Spriggan Wood": 17,
   "Butterfly Wing": 18,
   "Canis Root": 19,
   "Charred Skeever Hide": 20,
   "Chaurus Eggs": 21,
   "Chaurus Hunter Antennae": 22,
   "Chicken's Egg": 23,
   "Creep Cluster": 24,
   "Crimson Nirnroot": 25,
   "Cyrodilic Spadetail": 26,
   "Daedra Heart": 27,
   "Deathbell": 28,
   "Dragon's Tongue": 29,
   "Dwarven Oil": 30,
   "Ectoplasm": 31,
   "Elves Ear": 32,
   "Emperor Parasol Moss": 33,
   "Eye of Sabre Cat": 34,
   "Falmer Ear": 35,
   "Farengar's Frost Salt": 36,
   "Felsaad Tern Feathers": 37,
   "Fine-Cut Void Salts": 38,
   "Fire Salts": 39,
   "Fly Amanita": 40,
   "Frost Mirriam": 41,
   "Frost Salts": 42,
   "Garlic": 43,
   "Giant's Toe": 44,
   "Giant Lichen": 45,
   "Gleamblossom": 46,
   "Glow Dust": 47,
   "Glowing Mushroom": 48,
   "Grass Pod": 49,
   "Hagraven Claw": 50,
   "Hagraven Feathers": 51,
   "Hanging Moss": 52,
   "Hawk's Egg": 53,
   "Hawk Beak": 54,
   "Hawk Feathers": 55,
   "Histcarp": 56,
   "Honeycomb": 57,
   "Human Flesh": 58,
   "Human Heart": 59,
   "Ice Wraith Teeth": 60,
   "Imp Stool": 61,
   "Jarrin Root": 62,
   "Jazbay Grapes": 63,
   "Juniper Berries": 64,
   "Large Antlers": 65,
   "Lavender": 66,
   "Luna Moth Wing": 67,
   "Moon Sugar": 68,
   "Mora Tapinella": 69,
   "Mudcrab Chitin": 70,
   "Namira's Rot": 71,
   "Netch Jelly": 72,
   "Nightshade": 73,
   "Nirnroot": 74,
   "Nordic Barnacle": 75,
   "Orange Dartwing": 76,
   "Pearl": 77,
   "Pine Thrush Egg": 78,
   "Poison Bloom": 79,
   "Powdered Mammoth Tusk": 80,
   "Purple Mountain Flower": 81,
   "Red Mountain Flower": 82,
   "River Betty": 83,
   "Rock Warbler Egg": 84,
   "Sabre Cat Tooth": 85,
   "Salmon Roe": 86,
   "Salt Pile": 87,
   "Scaly Pholiota": 88,
   "Scathecraw": 89,
   "Silverside Perch": 90,
   "Skeever Tail": 91,
   "Slaughterfish Egg": 92,
   "Slaughterfish Scales": 93,
   "Small Antlers": 94,
   "Small Pearl": 95,
   "Snowberries": 96,
   "Spawn Ash": 97,
   "Spider Egg": 98,
   "Spriggan Sap": 99,
   "Swamp Fungal Pod": 100,
   "Taproot": 101,
   "Thistle Branch": 102,
   "Torchbug Thorax": 103,
   "Trama Root": 104,
   "Troll Fat": 105,
   "Tundra Cotton": 106,
   "Vampire Dust": 107,
   "Void Salts": 108,
   "Wheat": 109,
   "White Cap": 110,
   "Wisp Wrappings": 111,
   "Yellow Mountain Flower": 112
  },
  "z": 113,
  "a": [
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true
  ],
  "b": [
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false
  ],
  "d": [
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null
  ],
  "l": [
   {
    "n": "Abecean Longfin",
    "v": "15",
    "w": "0.5",
    "r": "Collected by catching Abacean Longfin fish.",
    "o": "BS",
    "q": "Common",
    "e": [
     {
      "x": 23,
      "v": 1,
      "m": 1
     },
     {
      "x": 25,
      "v": 1,
      "m": 1
     },
     {
      "x": 51,
      "v": 1,
      "m": 1
     },
     {
      "x": 53,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Ancestor Moth Wing",
    "v": "2",
    "w": "0.1",
    "r": "Collected by catching Ancestor Moths.",
    "o": "DG",
    "q": "None",
    "e": [
     {
      "x": 2,
      "v": 1,
      "m": 1
     },
     {
      "x": 5,
      "v": 1,
      "m": 1
     },
     {
      "x": 11,
      "v": 1,
      "m": 1
     },
     {
      "x": 13,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Ash Creep Cluster",
    "v": "20",
    "w": "0.25",
    "r": "Harvested from creep cluster plants unique to Solstheim.",
    "o": "DB",
    "q": "",
    "e": [
     {
      "x": 5,
      "v": 1,
      "m": 1
     },
     {
      "x": 12,
      "v": 1,
      "m": 1
     },
     {
      "x": 29,
      "v": 1,
      "m": 1
     },
     {
      "x": 40,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Ash Hopper Jelly",
    "v": "20",
    "w": "0.25",
    "r": "Collected from dead ash hoppers.",
    "o": "DB",
    "q": "",
    "e": [
     {
      "x": 17,
      "v": 1,
      "m": 1
     },
     {
      "x": 44,
      "v": 1,
      "m": 1
     },
     {
      "x": 45,
      "v": 1,
      "m": 1
     },
     {
      "x": 51,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Ashen Grass Pod",
    "v": "1",
    "w": "0.1",
    "r": "Harvested from spiky grass plants unique to Solstheim.",
    "o": "DB",
    "q": "",
    "e": [
     {
      "x": 18,
      "v": 1,
      "m": 1
     },
     {
      "x": 25,
      "v": 1,
      "m": 1
     },
     {
      "x": 40,
      "v": 1,
      "m": "1.34"
     },
     {
      "x": 54,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Bear Claws",
    "v": "2",
    "w": "0.1",
    "r": "Collected from various types of dead Bears.",
    "o": "BS",
    "q": "None (Uncommon)",
    "e": [
     {
      "x": 2,
      "v": 1,
      "m": 1
     },
     {
      "x": 14,
      "v": 1,
      "m": 1
     },
     {
      "x": 21,
      "v": 1,
      "m": 1
     },
     {
      "x": 47,
      "v": 1,
      "m": "0.8"
     }
    ]
   },
   {
    "n": "Bee",
    "v": "3",
    "w": "0.1",
    "r": "Collected from beehives and by catching Bees.",
    "o": "BS",
    "q": "Common",
    "e": [
     {
      "x": 36,
      "v": 1,
      "m": 1
     },
     {
      "x": 39,
      "v": 1,
      "m": 1
     },
     {
      "x": 47,
      "v": 1,
      "m": 1
     },
     {
      "x": 54,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Beehive Husk",
    "v": "5",
    "w": "1",
    "r": "Collected from beehives.",
    "o": "BS",
    "q": "None (Common)",
    "e": [
     {
      "x": 12,
      "v": 1,
      "m": 1
     },
     {
      "x": 17,
      "v": 1,
      "m": 1
     },
     {
      "x": 25,
      "v": 1,
      "m": 1
     },
     {
      "x": 43,
      "v": 1,
      "m": "0.5"
     }
    ]
   },
   {
    "n": "Berit's Ashes",
    "v": "5",
    "w": "0.2",
    "r": "This ingredient is given as a quest item. Its effects are all identical to standard Bone Meal.",
    "o": "BS",
    "q": "None",
    "e": [
     {
      "x": 5,
      "v": 1,
      "m": 1
     },
     {
      "x": 11,
      "v": 1,
      "m": 1
     },
     {
      "x": 36,
      "v": 1,
      "m": 1
     },
     {
      "x": 40,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Bleeding Crown",
    "v": "10",
    "w": "0.3",
    "r": "Harvested from Bleeding Crown, a mushroom found in various caves.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 9,
      "v": 1,
      "m": 1
     },
     {
      "x": 42,
      "v": 1,
      "m": 1
     },
     {
      "x": 50,
      "v": 1,
      "m": 1
     },
     {
      "x": 53,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Blisterwort",
    "v": "12",
    "w": "0.2",
    "r": "Harvested from Blisterwort mushrooms found in various caves.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 5,
      "v": 1,
      "m": 1
     },
     {
      "x": 24,
      "v": 1,
      "m": 1
     },
     {
      "x": 28,
      "v": 1,
      "m": 1
     },
     {
      "x": 45,
      "v": 1,
      "m": "0.6"
     }
    ]
   },
   {
    "n": "Blue Butterfly Wing",
    "v": "2",
    "w": "0.1",
    "r": "Collected by catching Blue Butterflies. Often found during daylight hours near flowering plants.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 2,
      "v": 1,
      "m": 1
     },
     {
      "x": 5,
      "v": 1,
      "m": 1
     },
     {
      "x": 11,
      "v": 1,
      "m": 1
     },
     {
      "x": 13,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Blue Dartwing",
    "v": "1",
    "w": "0.1",
    "r": "Collected by catching Dragonflies found near rivers and streams below the snow line.",
    "o": "BS",
    "q": "None (Uncommon)",
    "e": [
     {
      "x": 6,
      "v": 1,
      "m": 1
     },
     {
      "x": 22,
      "v": 1,
      "m": 1
     },
     {
      "x": 44,
      "v": 1,
      "m": 1
     },
     {
      "x": 45,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Blue Mountain Flower",
    "v": "2",
    "w": "0.1",
    "r": "Harvested from the blue variety of Mountain Flower, found throughout Skyrim.",
    "o": "BS",
    "q": "Common",
    "e": [
     {
      "x": 2,
      "v": 1,
      "m": 1
     },
     {
      "x": 11,
      "v": 1,
      "m": 1
     },
     {
      "x": 14,
      "v": 1,
      "m": 1
     },
     {
      "x": 45,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Boar Tusk",
    "v": "20",
    "w": "0.5",
    "r": "Collected from dead bristlebacks and rieklings.",
    "o": "DB",
    "q": "",
    "e": [
     {
      "x": 9,
      "v": 1,
      "m": 1
     },
     {
      "x": 14,
      "v": "5.9",
      "m": 1
     },
     {
      "x": 26,
      "v": "1.25",
      "m": "5.9"
     },
     {
      "x": 28,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Bone Meal",
    "v": "5",
    "w": "0.5",
    "r": "Collected from undead such as skeletons, and Draugr.",
    "o": "BS",
    "q": "Common",
    "e": [
     {
      "x": 5,
      "v": 1,
      "m": 1
     },
     {
      "x": 11,
      "v": 1,
      "m": 1
     },
     {
      "x": 36,
      "v": 1,
      "m": 1
     },
     {
      "x": 40,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Briar Heart",
    "v": "20",
    "w": "0.5",
    "r": "Collected from Forsworn Briarhearts.",
    "o": "BS",
    "q": "Rare",
    "e": [
     {
      "x": 9,
      "v": 1,
      "m": "0.5"
     },
     {
      "x": 19,
      "v": 1,
      "m": 1
     },
     {
      "x": 33,
      "v": 1,
      "m": 1
     },
     {
      "x": 46,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Burnt Spriggan Wood",
    "v": "20",
    "w": "0.5",
    "r": "Collected from dead burnt spriggans.",
    "o": "DB",
    "q": "",
    "e": [
     {
      "x": 2,
      "v": 1,
      "m": 1
     },
     {
      "x": 7,
      "v": 1,
      "m": 1
     },
     {
      "x": 48,
      "v": 1,
      "m": 1
     },
     {
      "x": 50,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Butterfly Wing",
    "v": "3",
    "w": "0.1",
    "r": "Collected from catching Monarch Butterflies. Often found during daylight hours near flowering plants.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 3,
      "v": 1,
      "m": 1
     },
     {
      "x": 8,
      "v": 1,
      "m": 1
     },
     {
      "x": 32,
      "v": 1,
      "m": 1
     },
     {
      "x": 45,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Canis Root",
    "v": "5",
    "w": "0.1",
    "r": "Harvested from Canis Root, found in The Rift and Hjaalmarch.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 5,
      "v": 1,
      "m": 1
     },
     {
      "x": 20,
      "v": 1,
      "m": 1
     },
     {
      "x": 21,
      "v": 1,
      "m": 1
     },
     {
      "x": 33,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Charred Skeever Hide",
    "v": "1",
    "w": "0.5",
    "r": "Food, collected from dead Skeevers found on roasting spits.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 0,
      "v": "0.36",
      "m": 1
     },
     {
      "x": 43,
      "v": 1,
      "m": 1
     },
     {
      "x": 45,
      "v": 1,
      "m": 1
     },
     {
      "x": 47,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Chaurus Eggs",
    "v": "10",
    "w": "0.2",
    "r": "Collected from Chaurus Egg Sacs, found in Falmer caves.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 3,
      "v": 1,
      "m": 1
     },
     {
      "x": 26,
      "v": 1,
      "m": 1
     },
     {
      "x": 29,
      "v": 1,
      "m": 1
     },
     {
      "x": 53,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Chaurus Hunter Antennae",
    "v": "2",
    "w": "0.1",
    "r": "Collected from dead Chaurus Hunters and Chaurus Hunter Fledglings.",
    "o": "DG",
    "q": "None",
    "e": [
     {
      "x": 2,
      "v": 1,
      "m": 1
     },
     {
      "x": 5,
      "v": 1,
      "m": 1
     },
     {
      "x": 11,
      "v": 1,
      "m": 1
     },
     {
      "x": 13,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Chicken's Egg",
    "v": "2",
    "w": "0.5",
    "r": "Food, harvested from Chicken nests in various farms.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 2,
      "v": 1,
      "m": 1
     },
     {
      "x": 32,
      "v": 1,
      "m": 1
     },
     {
      "x": 42,
      "v": 1,
      "m": 1
     },
     {
      "x": 49,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Creep Cluster",
    "v": "1",
    "w": "0.2",
    "r": "Harvested from Creep Cluster, found in the volcanic tundra of Eastmarch.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 4,
      "v": 1,
      "m": 1
     },
     {
      "x": 10,
      "v": 1,
      "m": 1
     },
     {
      "x": 46,
      "v": 1,
      "m": 1
     },
     {
      "x": 52,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Crimson Nirnroot",
    "v": "10",
    "w": "0.2",
    "r": "Harvested from Crimson Nirnroot, found in Blackreach, needed for the quest A Return To Your Roots.",
    "o": "BS",
    "q": "None",
    "e": [
     {
      "x": 1,
      "v": 1,
      "m": "3"
     },
     {
      "x": 5,
      "v": 1,
      "m": "3"
     },
     {
      "x": 29,
      "v": 1,
      "m": 1
     },
     {
      "x": 42,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Cyrodilic Spadetail",
    "v": "15",
    "w": "0.25",
    "r": "Collected by catching Cyrodilic Spadetail fish.",
    "o": "BS",
    "q": "Common",
    "e": [
     {
      "x": 5,
      "v": 1,
      "m": 1
     },
     {
      "x": 6,
      "v": 1,
      "m": 1
     },
     {
      "x": 23,
      "v": 1,
      "m": 1
     },
     {
      "x": 34,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Daedra Heart",
    "v": "250",
    "w": "0.5",
    "r": "Collected from dead Dremora.",
    "o": "BS",
    "q": "Rare",
    "e": [
     {
      "x": 3,
      "v": 1,
      "m": 1
     },
     {
      "x": 4,
      "v": 1,
      "m": 1
     },
     {
      "x": 6,
      "v": 1,
      "m": 1
     },
     {
      "x": 45,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Deathbell",
    "v": "4",
    "w": "0.1",
    "r": "Harvested from Deathbell, found in Hjaalmarch.",
    "o": "BS",
    "q": "Rare",
    "e": [
     {
      "x": 1,
      "v": 1,
      "m": "1.5"
     },
     {
      "x": 36,
      "v": "2.1",
      "m": 1
     },
     {
      "x": 48,
      "v": 1,
      "m": 1
     },
     {
      "x": 53,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Dragon's Tongue",
    "v": "5",
    "w": "0.1",
    "r": "Harvested from Dragon's Tongue, found in the volcanic tundra of Eastmarch.",
    "o": "BS",
    "q": "Common",
    "e": [
     {
      "x": 8,
      "v": 1,
      "m": 1
     },
     {
      "x": 16,
      "v": 1,
      "m": 1
     },
     {
      "x": 27,
      "v": 1,
      "m": 1
     },
     {
      "x": 40,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Dwarven Oil",
    "v": "15",
    "w": "0.25",
    "r": "Collected from destroyed Dwarven Automatons, found in Dwarven Ruins.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 16,
      "v": 1,
      "m": 1
     },
     {
      "x": 38,
      "v": 1,
      "m": 1
     },
     {
      "x": 46,
      "v": 1,
      "m": 1
     },
     {
      "x": 52,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Ectoplasm",
    "v": "25",
    "w": "0.1",
    "r": "Collected from undead Ghosts.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 1,
      "v": 1,
      "m": 1
     },
     {
      "x": 12,
      "v": 1,
      "m": "0.8"
     },
     {
      "x": 19,
      "v": 1,
      "m": 1
     },
     {
      "x": 46,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Elves Ear",
    "v": "10",
    "w": "0.1",
    "r": "Harvested from Dried Elves Ear bunches found in homes and camps.",
    "o": "BS",
    "q": "Common",
    "e": [
     {
      "x": 20,
      "v": 1,
      "m": 1
     },
     {
      "x": 40,
      "v": 1,
      "m": 1
     },
     {
      "x": 46,
      "v": 1,
      "m": 1
     },
     {
      "x": 51,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Emperor Parasol Moss",
    "v": "1",
    "w": "0.25",
    "r": "Harvested from emperor parasol moss plants near Tel Mithryn.",
    "o": "DB",
    "q": "",
    "e": [
     {
      "x": 1,
      "v": 1,
      "m": 1
     },
     {
      "x": 19,
      "v": 1,
      "m": 1
     },
     {
      "x": 27,
      "v": 1,
      "m": 1
     },
     {
      "x": 37,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Eye of Sabre Cat",
    "v": "2",
    "w": "0.1",
    "r": "Collected from dead Sabre Cats.",
    "o": "BS",
    "q": "None (Uncommon)",
    "e": [
     {
      "x": 3,
      "v": 1,
      "m": 1
     },
     {
      "x": 34,
      "v": 1,
      "m": 1
     },
     {
      "x": 45,
      "v": 1,
      "m": 1
     },
     {
      "x": 47,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Falmer Ear",
    "v": "10",
    "w": "0.2",
    "r": "Collected from dead Falmer.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 1,
      "v": 1,
      "m": 1
     },
     {
      "x": 18,
      "v": 1,
      "m": 1
     },
     {
      "x": 28,
      "v": 1,
      "m": 1
     },
     {
      "x": 43,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Farengar's Frost Salt",
    "v": "100",
    "w": "0.25",
    "r": "This ingredient is given as a quest item. It is identical to standard Frost Salts, except for its name.",
    "o": "BS",
    "q": "None",
    "e": [
     {
      "x": 11,
      "v": 1,
      "m": 1
     },
     {
      "x": 41,
      "v": 1,
      "m": 1
     },
     {
      "x": 46,
      "v": 1,
      "m": 1
     },
     {
      "x": 50,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Felsaad Tern Feathers",
    "v": "15",
    "w": "0.1",
    "r": "Collected from dead Felsaad terns.",
    "o": "DB",
    "q": "",
    "e": [
     {
      "x": 0,
      "v": 1,
      "m": 1
     },
     {
      "x": 17,
      "v": 1,
      "m": 1
     },
     {
      "x": 42,
      "v": 1,
      "m": 1
     },
     {
      "x": 45,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Fine-Cut Void Salts",
    "v": "125",
    "w": "0.2",
    "r": "This ingredient is given as a quest item. It is identical to standard Void Salts, except for its name.",
    "o": "BS",
    "q": "None",
    "e": [
     {
      "x": 1,
      "v": 1,
      "m": 1
     },
     {
      "x": 19,
      "v": 1,
      "m": 1
     },
     {
      "x": 42,
      "v": 1,
      "m": 1
     },
     {
      "x": 54,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Fire Salts",
    "v": "50",
    "w": "0.25",
    "r": "Collected from dead Flame Atronachs, a type of daedra.",
    "o": "BS",
    "q": "Rare",
    "e": [
     {
      "x": 38,
      "v": 1,
      "m": 1
     },
     {
      "x": 40,
      "v": 1,
      "m": 1
     },
     {
      "x": 46,
      "v": 1,
      "m": 1
     },
     {
      "x": 51,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Fly Amanita",
    "v": "2",
    "w": "0.1",
    "r": "Harvested from Fly Amanita mushrooms, found in various caves.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 27,
      "v": 1,
      "m": 1
     },
     {
      "x": 28,
      "v": 1,
      "m": 1
     },
     {
      "x": 39,
      "v": 1,
      "m": 1
     },
     {
      "x": 40,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Frost Mirriam",
    "v": "1",
    "w": "0.1",
    "r": "Harvested from Dried Frost Mirriam bunches found in homes and camps.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 4,
      "v": 1,
      "m": 1
     },
     {
      "x": 25,
      "v": 1,
      "m": 1
     },
     {
      "x": 35,
      "v": 1,
      "m": 1
     },
     {
      "x": 41,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Frost Salts",
    "v": "100",
    "w": "0.25",
    "r": "Collected from dead Frost Atronachs, a type of daedra.",
    "o": "BS",
    "q": "Rare",
    "e": [
     {
      "x": 11,
      "v": 1,
      "m": 1
     },
     {
      "x": 41,
      "v": 1,
      "m": 1
     },
     {
      "x": 46,
      "v": 1,
      "m": 1
     },
     {
      "x": 50,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Garlic",
    "v": "1",
    "w": "0.25",
    "r": "Food. Can also be harvested from Garlic Braids.",
    "o": "BS",
    "q": "Common",
    "e": [
     {
      "x": 26,
      "v": 1,
      "m": 1
     },
     {
      "x": 37,
      "v": 1,
      "m": 1
     },
     {
      "x": 38,
      "v": 1,
      "m": 1
     },
     {
      "x": 43,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Giant's Toe",
    "v": "20",
    "w": "1",
    "r": "Collected from dead Giants, which can be found in Giant Camps.",
    "o": "BS",
    "q": "Rare",
    "e": [
     {
      "x": 4,
      "v": 1,
      "m": 1
     },
     {
      "x": 5,
      "v": 1,
      "m": 1
     },
     {
      "x": 10,
      "v": 1,
      "m": 1
     },
     {
      "x": 14,
      "v": "5.9",
      "m": 1
     }
    ]
   },
   {
    "n": "Giant Lichen",
    "v": "5",
    "w": "0.25",
    "r": "Harvested from Giant Lichen, found in Hjaalmarch.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 34,
      "v": 1,
      "m": 1
     },
     {
      "x": 46,
      "v": 1,
      "m": 1
     },
     {
      "x": 53,
      "v": 1,
      "m": 1
     },
     {
      "x": 54,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Gleamblossom",
    "v": "5",
    "w": "0.1",
    "r": "Harvested from the plant of the same name.",
    "o": "DG",
    "q": "None",
    "e": [
     {
      "x": 6,
      "v": 1,
      "m": 1
     },
     {
      "x": 33,
      "v": 1,
      "m": 1
     },
     {
      "x": 37,
      "v": 1,
      "m": 1
     },
     {
      "x": 42,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Glow Dust",
    "v": "20",
    "w": "0.5",
    "r": "Collected from dead Wisps and Wispmothers.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 2,
      "v": 1,
      "m": 1
     },
     {
      "x": 3,
      "v": 1,
      "m": 1
     },
     {
      "x": 12,
      "v": 1,
      "m": 1
     },
     {
      "x": 44,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Glowing Mushroom",
    "v": "5",
    "w": "0.2",
    "r": "Harvested from Glowing Mushrooms, found in various caves.",
    "o": "BS",
    "q": "None",
    "e": [
     {
      "x": 12,
      "v": 1,
      "m": 1
     },
     {
      "x": 14,
      "v": 1,
      "m": 1
     },
     {
      "x": 24,
      "v": 1,
      "m": 1
     },
     {
      "x": 44,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Grass Pod",
    "v": "1",
    "w": "0.1",
    "r": "Harvested from Spiky Grass, found in northern regions of Skyrim.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 7,
      "v": 1,
      "m": 1
     },
     {
      "x": 35,
      "v": 1,
      "m": 1
     },
     {
      "x": 43,
      "v": 1,
      "m": 1
     },
     {
      "x": 46,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Hagraven Claw",
    "v": "20",
    "w": "0.25",
    "r": "Collected from dead Hagravens.",
    "o": "BS",
    "q": "Rare",
    "e": [
     {
      "x": 8,
      "v": 1,
      "m": 1
     },
     {
      "x": 13,
      "v": 1,
      "m": 1
     },
     {
      "x": 31,
      "v": 1,
      "m": 1
     },
     {
      "x": 42,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Hagraven Feathers",
    "v": "20",
    "w": "0.1",
    "r": "Collected from dead Hagravens. Can also be found scattered around their sleeping areas.",
    "o": "BS",
    "q": "Rare",
    "e": [
     {
      "x": 3,
      "v": 1,
      "m": 1
     },
     {
      "x": 11,
      "v": 1,
      "m": 1
     },
     {
      "x": 28,
      "v": 1,
      "m": 1
     },
     {
      "x": 54,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Hanging Moss",
    "v": "1",
    "w": "0.25",
    "r": "Harvested from Hanging Moss.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 2,
      "v": 1,
      "m": 1
     },
     {
      "x": 3,
      "v": 1,
      "m": 1
     },
     {
      "x": 14,
      "v": 1,
      "m": 1
     },
     {
      "x": 21,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Hawk's Egg",
    "v": "5",
    "w": "0.5",
    "r": "Harvested from Hawk nests.",
    "o": "HF",
    "q": "None",
    "e": [
     {
      "x": 2,
      "v": 1,
      "m": 1
     },
     {
      "x": 32,
      "v": 1,
      "m": 1
     },
     {
      "x": 42,
      "v": 1,
      "m": 1
     },
     {
      "x": 49,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Hawk Beak",
    "v": "15",
    "w": "0.25",
    "r": "Collected from dead Hawks.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 10,
      "v": 1,
      "m": 1
     },
     {
      "x": 41,
      "v": 1,
      "m": 1
     },
     {
      "x": 44,
      "v": 1,
      "m": 1
     },
     {
      "x": 47,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Hawk Feathers",
    "v": "15",
    "w": "0.1",
    "r": "Collected from dead Hawks.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 0,
      "v": 1,
      "m": 1
     },
     {
      "x": 17,
      "v": 1,
      "m": 1
     },
     {
      "x": 21,
      "v": 1,
      "m": 1
     },
     {
      "x": 25,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Histcarp",
    "v": "6",
    "w": "0.25",
    "r": "Collected by catching Histcarp fish.",
    "o": "BS",
    "q": "Common",
    "e": [
     {
      "x": 4,
      "v": 1,
      "m": 1
     },
     {
      "x": 19,
      "v": 1,
      "m": 1
     },
     {
      "x": 47,
      "v": 1,
      "m": 1
     },
     {
      "x": 49,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Honeycomb",
    "v": "5",
    "w": "1",
    "r": "Food. Collected from beehives.",
    "o": "BS",
    "q": "None (Common)",
    "e": [
     {
      "x": 9,
      "v": 1,
      "m": "0.5"
     },
     {
      "x": 17,
      "v": 1,
      "m": 1
     },
     {
      "x": 36,
      "v": 1,
      "m": 1
     },
     {
      "x": 47,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Human Flesh",
    "v": "1",
    "w": "0.25",
    "r": "Cannot be harvested or collected; with the Dawnguard plug-in installed, several respawning samples can be found in Volkihar Keep.",
    "o": "BS",
    "q": "None",
    "e": [
     {
      "x": 1,
      "v": 1,
      "m": 1
     },
     {
      "x": 25,
      "v": 1,
      "m": 1
     },
     {
      "x": 33,
      "v": 1,
      "m": 1
     },
     {
      "x": 46,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Human Heart",
    "v": "0",
    "w": "1",
    "r": "Cannot be harvested or collected; limited number of samples available.",
    "o": "BS",
    "q": "None",
    "e": [
     {
      "x": 1,
      "v": 1,
      "m": 1
     },
     {
      "x": 2,
      "v": 1,
      "m": 1
     },
     {
      "x": 3,
      "v": 1,
      "m": 1
     },
     {
      "x": 28,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Ice Wraith Teeth",
    "v": "30",
    "w": "0.25",
    "r": "Collected from Ice Wraiths.",
    "o": "BS",
    "q": "Rare",
    "e": [
     {
      "x": 15,
      "v": 1,
      "m": 1
     },
     {
      "x": 29,
      "v": 1,
      "m": 1
     },
     {
      "x": 50,
      "v": 1,
      "m": 1
     },
     {
      "x": 51,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Imp Stool",
    "v": "0",
    "w": "0.3",
    "r": "Harvested from Imp Stool mushrooms, found in various caves.",
    "o": "BS",
    "q": "Rare",
    "e": [
     {
      "x": 1,
      "v": 1,
      "m": 1
     },
     {
      "x": 30,
      "v": 1,
      "m": 1
     },
     {
      "x": 33,
      "v": 1,
      "m": 1
     },
     {
      "x": 45,
      "v": 1,
      "m": "0.6"
     }
    ]
   },
   {
    "n": "Jarrin Root",
    "v": "10",
    "w": "0.5",
    "r": "You may only receive this ingredient once during the Dark Brotherhood quest line.",
    "o": "BS",
    "q": "None",
    "e": [
     {
      "x": 1,
      "v": 1,
      "m": "100"
     },
     {
      "x": 2,
      "v": 1,
      "m": 1
     },
     {
      "x": 3,
      "v": 1,
      "m": 1
     },
     {
      "x": 5,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Jazbay Grapes",
    "v": "1",
    "w": "0.2",
    "r": "Harvested from Jazbay vines, found in the volcanic tundra of Eastmarch.",
    "o": "BS",
    "q": "Rare",
    "e": [
     {
      "x": 19,
      "v": 1,
      "m": 1
     },
     {
      "x": 34,
      "v": 1,
      "m": 1
     },
     {
      "x": 38,
      "v": 1,
      "m": 1
     },
     {
      "x": 52,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Juniper Berries",
    "v": "1",
    "w": "0.1",
    "r": "Harvested from Juniper shrubs, common in The Reach.",
    "o": "BS",
    "q": "Common",
    "e": [
     {
      "x": 4,
      "v": 1,
      "m": 1
     },
     {
      "x": 20,
      "v": 1,
      "m": 1
     },
     {
      "x": 37,
      "v": 1,
      "m": 1
     },
     {
      "x": 50,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Large Antlers",
    "v": "2",
    "w": "0.1",
    "r": "Collected from dead male Elk.",
    "o": "BS",
    "q": "None (Uncommon)",
    "e": [
     {
      "x": 4,
      "v": 1,
      "m": 1
     },
     {
      "x": 26,
      "v": 1,
      "m": 1
     },
     {
      "x": 47,
      "v": 1,
      "m": 1
     },
     {
      "x": 48,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Lavender",
    "v": "1",
    "w": "0.1",
    "r": "Harvested from Lavender, most common in Whiterun Hold.",
    "o": "BS",
    "q": "Common",
    "e": [
     {
      "x": 11,
      "v": 1,
      "m": 1
     },
     {
      "x": 26,
      "v": 1,
      "m": 1
     },
     {
      "x": 35,
      "v": 1,
      "m": 1
     },
     {
      "x": 42,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Luna Moth Wing",
    "v": "5",
    "w": "0.1",
    "r": "Collected by catching Luna Moths. Often found near flowers after dark.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 3,
      "v": 1,
      "m": 1
     },
     {
      "x": 17,
      "v": 1,
      "m": 1
     },
     {
      "x": 29,
      "v": 1,
      "m": 1
     },
     {
      "x": 37,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Moon Sugar",
    "v": "50",
    "w": "0.25",
    "r": "Cannot be collected or harvested. Can be purchased from the Khajiit Traders.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 38,
      "v": 1,
      "m": 1
     },
     {
      "x": 41,
      "v": 1,
      "m": 1
     },
     {
      "x": 46,
      "v": 1,
      "m": 1
     },
     {
      "x": 50,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Mora Tapinella",
    "v": "4",
    "w": "0.25",
    "r": "Harvested from Mora Tapinella mushrooms, found growing on dead trees.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 16,
      "v": 1,
      "m": 1
     },
     {
      "x": 30,
      "v": 1,
      "m": 1
     },
     {
      "x": 39,
      "v": 1,
      "m": 1
     },
     {
      "x": 46,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Mudcrab Chitin",
    "v": "2",
    "w": "0.25",
    "r": "Collected from dead Mudcrabs, found in or near bodies of water.",
    "o": "BS",
    "q": "None (Common)",
    "e": [
     {
      "x": 0,
      "v": 1,
      "m": 1
     },
     {
      "x": 40,
      "v": 1,
      "m": 1
     },
     {
      "x": 43,
      "v": 1,
      "m": 1
     },
     {
      "x": 47,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Namira's Rot",
    "v": "0",
    "w": "0.25",
    "r": "Harvested from Namira's Rot mushrooms, found in various caves.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 3,
      "v": 1,
      "m": 1
     },
     {
      "x": 6,
      "v": 1,
      "m": 1
     },
     {
      "x": 18,
      "v": 1,
      "m": 1
     },
     {
      "x": 37,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Netch Jelly",
    "v": "20",
    "w": "0.5",
    "r": "Collected from dead netch.",
    "o": "DB",
    "q": "",
    "e": [
     {
      "x": 6,
      "v": 1,
      "m": 1
     },
     {
      "x": 10,
      "v": 1,
      "m": 1
     },
     {
      "x": 33,
      "v": 1,
      "m": 1
     },
     {
      "x": 47,
      "v": 1,
      "m": "2"
     }
    ]
   },
   {
    "n": "Nightshade",
    "v": "8",
    "w": "0.1",
    "r": "Harvested from Nightshade, found growing throughout Skyrim.",
    "o": "BS",
    "q": "Rare",
    "e": [
     {
      "x": 1,
      "v": 1,
      "m": 1
     },
     {
      "x": 2,
      "v": 1,
      "m": 1
     },
     {
      "x": 12,
      "v": 1,
      "m": "0.8"
     },
     {
      "x": 32,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Nirnroot",
    "v": "10",
    "w": "0.2",
    "r": "Harvested from Nirnroot, found near bodies of water throughout Skyrim.",
    "o": "BS",
    "q": "Rare",
    "e": [
     {
      "x": 1,
      "v": "12.6",
      "m": 1
     },
     {
      "x": 5,
      "v": 1,
      "m": 1
     },
     {
      "x": 29,
      "v": 1,
      "m": 1
     },
     {
      "x": 42,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Nordic Barnacle",
    "v": "5",
    "w": "0.2",
    "r": "Harvested from Nordic Barnacle Clusters, found in or near water.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 3,
      "v": 1,
      "m": 1
     },
     {
      "x": 22,
      "v": 1,
      "m": 1
     },
     {
      "x": 37,
      "v": 1,
      "m": 1
     },
     {
      "x": 49,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Orange Dartwing",
    "v": "1",
    "w": "0.1",
    "r": "Collected by catching Dragonflies found near rivers and streams below the snow line.",
    "o": "BS",
    "q": "None (Common)",
    "e": [
     {
      "x": 22,
      "v": 1,
      "m": 1
     },
     {
      "x": 30,
      "v": 1,
      "m": 1
     },
     {
      "x": 35,
      "v": 1,
      "m": 1
     },
     {
      "x": 47,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Pearl",
    "v": "2",
    "w": "0.1",
    "r": "Cannot be harvested or collected in the original version of the game; only readily available after the Merchant perk has been unlocked. With Dragonborn, they can be harvested from Pearl Oysters in Solstheim.",
    "o": "BS",
    "q": "None (Uncommon)",
    "e": [
     {
      "x": 9,
      "v": 1,
      "m": 1
     },
     {
      "x": 44,
      "v": 1,
      "m": 1
     },
     {
      "x": 46,
      "v": 1,
      "m": 1
     },
     {
      "x": 47,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Pine Thrush Egg",
    "v": "2",
    "w": "0.5",
    "r": "Harvested from bird nests in forested regions, in particular The Rift.",
    "o": "BS",
    "q": "Common",
    "e": [
     {
      "x": 18,
      "v": 1,
      "m": 1
     },
     {
      "x": 44,
      "v": 1,
      "m": 1
     },
     {
      "x": 47,
      "v": 1,
      "m": 1
     },
     {
      "x": 53,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Poison Bloom",
    "v": "5",
    "w": "0.25",
    "r": "Harvested from the plant of the same name.",
    "o": "DG",
    "q": "None",
    "e": [
     {
      "x": 1,
      "v": 1,
      "m": "1.5"
     },
     {
      "x": 6,
      "v": 1,
      "m": 1
     },
     {
      "x": 10,
      "v": 1,
      "m": 1
     },
     {
      "x": 48,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Powdered Mammoth Tusk",
    "v": "2",
    "w": "0.1",
    "r": "Cannot be harvested or collected; only readily available after the Merchant perk has been unlocked.",
    "o": "BS",
    "q": "None (Uncommon)",
    "e": [
     {
      "x": 6,
      "v": 1,
      "m": 1
     },
     {
      "x": 25,
      "v": 1,
      "m": 1
     },
     {
      "x": 47,
      "v": 1,
      "m": 1
     },
     {
      "x": 50,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Purple Mountain Flower",
    "v": "2",
    "w": "0.1",
    "r": "Harvested from the purple variety of Mountain Flower.",
    "o": "BS",
    "q": "Common",
    "e": [
     {
      "x": 25,
      "v": 1,
      "m": 1
     },
     {
      "x": 31,
      "v": 1,
      "m": 1
     },
     {
      "x": 41,
      "v": 1,
      "m": 1
     },
     {
      "x": 47,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Red Mountain Flower",
    "v": "2",
    "w": "0.1",
    "r": "Harvested from the red variety of Mountain Flower.",
    "o": "BS",
    "q": "Common",
    "e": [
     {
      "x": 1,
      "v": 1,
      "m": 1
     },
     {
      "x": 19,
      "v": 1,
      "m": 1
     },
     {
      "x": 35,
      "v": 1,
      "m": 1
     },
     {
      "x": 46,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "River Betty",
    "v": "15",
    "w": "0.25",
    "r": "Collected by catching River Betty fish.",
    "o": "BS",
    "q": "Common",
    "e": [
     {
      "x": 1,
      "v": 1,
      "m": "2.5"
     },
     {
      "x": 7,
      "v": 1,
      "m": 1
     },
     {
      "x": 10,
      "v": 1,
      "m": 1
     },
     {
      "x": 48,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Rock Warbler Egg",
    "v": "2",
    "w": "0.5",
    "r": "Harvested from bird nests in rocky regions, in particular The Reach.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 5,
      "v": 1,
      "m": 1
     },
     {
      "x": 21,
      "v": 1,
      "m": 1
     },
     {
      "x": 45,
      "v": 1,
      "m": 1
     },
     {
      "x": 52,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Sabre Cat Tooth",
    "v": "2",
    "w": "0.1",
    "r": "Collected from dead Sabre cats.",
    "o": "BS",
    "q": "None (Uncommon)",
    "e": [
     {
      "x": 15,
      "v": 1,
      "m": 1
     },
     {
      "x": 24,
      "v": 1,
      "m": 1
     },
     {
      "x": 47,
      "v": 1,
      "m": 1
     },
     {
      "x": 53,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Salmon Roe",
    "v": "5",
    "w": "0.2",
    "r": "Harvested from jumping Salmon.",
    "o": "HF",
    "q": "None",
    "e": [
     {
      "x": 19,
      "v": "12.5",
      "m": "1.05"
     },
     {
      "x": 38,
      "v": 1,
      "m": 1
     },
     {
      "x": 47,
      "v": 1,
      "m": "0.4"
     },
     {
      "x": 49,
      "v": "15.4",
      "m": 1
     }
    ]
   },
   {
    "n": "Salt Pile",
    "v": "2",
    "w": "0.2",
    "r": "Food. Cannot be harvested or collected, but is commonly found in barrels and sacks.",
    "o": "BS",
    "q": "Common",
    "e": [
     {
      "x": 23,
      "v": 1,
      "m": 1
     },
     {
      "x": 38,
      "v": 1,
      "m": 1
     },
     {
      "x": 48,
      "v": 1,
      "m": 1
     },
     {
      "x": 52,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Scaly Pholiota",
    "v": "4",
    "w": "0.25",
    "r": "Harvested from Scaly Pholiota mushrooms, found growing on dead trees.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 10,
      "v": 1,
      "m": 1
     },
     {
      "x": 16,
      "v": 1,
      "m": 1
     },
     {
      "x": 39,
      "v": 1,
      "m": 1
     },
     {
      "x": 52,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Scathecraw",
    "v": "1",
    "w": "0.1",
    "r": "Harvested from scathecraw plants.",
    "o": "DB",
    "q": "",
    "e": [
     {
      "x": 30,
      "v": 1,
      "m": 1
     },
     {
      "x": 34,
      "v": 1,
      "m": 1
     },
     {
      "x": 35,
      "v": 1,
      "m": 1
     },
     {
      "x": 36,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Silverside Perch",
    "v": "15",
    "w": "0.25",
    "r": "Collected by catching Silverside Perch fish.",
    "o": "BS",
    "q": "Common",
    "e": [
     {
      "x": 4,
      "v": 1,
      "m": 1
     },
     {
      "x": 34,
      "v": 1,
      "m": 1
     },
     {
      "x": 41,
      "v": 1,
      "m": 1
     },
     {
      "x": 47,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Skeever Tail",
    "v": "3",
    "w": "0.2",
    "r": "Collected from dead Skeevers.",
    "o": "BS",
    "q": "Common",
    "e": [
     {
      "x": 1,
      "v": 1,
      "m": 1
     },
     {
      "x": 4,
      "v": 1,
      "m": 1
     },
     {
      "x": 17,
      "v": 1,
      "m": 1
     },
     {
      "x": 34,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Slaughterfish Egg",
    "v": "3",
    "w": "0.2",
    "r": "Collected from Slaughterfish Egg Nests, found in or near water.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 22,
      "v": 1,
      "m": 1
     },
     {
      "x": 26,
      "v": 1,
      "m": 1
     },
     {
      "x": 30,
      "v": 1,
      "m": 1
     },
     {
      "x": 43,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Slaughterfish Scales",
    "v": "3",
    "w": "0.1",
    "r": "Collected from dead Slaughterfish.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 9,
      "v": 1,
      "m": 1
     },
     {
      "x": 15,
      "v": 1,
      "m": 1
     },
     {
      "x": 30,
      "v": 1,
      "m": 1
     },
     {
      "x": 41,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Small Antlers",
    "v": "2",
    "w": "0.1",
    "r": "Collected from dead female Elk.",
    "o": "BS",
    "q": "None (Common)",
    "e": [
     {
      "x": 1,
      "v": 1,
      "m": 1
     },
     {
      "x": 23,
      "v": 1,
      "m": 1
     },
     {
      "x": 32,
      "v": 1,
      "m": 1
     },
     {
      "x": 53,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Small Pearl",
    "v": "2",
    "w": "0.1",
    "r": "Cannot be harvested or collected in the original version of the game; only readily available after the Merchant perk has been unlocked. With Dragonborn, they can be harvested from Pearl Oysters in Solstheim.",
    "o": "BS",
    "q": "None (Uncommon)",
    "e": [
     {
      "x": 21,
      "v": 1,
      "m": 1
     },
     {
      "x": 23,
      "v": 1,
      "m": 1
     },
     {
      "x": 41,
      "v": 1,
      "m": 1
     },
     {
      "x": 47,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Snowberries",
    "v": "4",
    "w": "0.1",
    "r": "Harvested from Snowberry bushes, found in snowy regions of Skyrim.",
    "o": "BS",
    "q": "Common",
    "e": [
     {
      "x": 13,
      "v": 1,
      "m": 1
     },
     {
      "x": 40,
      "v": 1,
      "m": 1
     },
     {
      "x": 41,
      "v": 1,
      "m": 1
     },
     {
      "x": 44,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Spawn Ash",
    "v": "20",
    "w": "0.1",
    "r": "Collected from dead ash spawn.",
    "o": "DB",
    "q": "",
    "e": [
     {
      "x": 13,
      "v": 1,
      "m": 1
     },
     {
      "x": 35,
      "v": 1,
      "m": 1
     },
     {
      "x": 36,
      "v": 1,
      "m": 1
     },
     {
      "x": 40,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Spider Egg",
    "v": "5",
    "w": "0.2",
    "r": "Collected from spider Egg Sacs and Web Sacs.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 2,
      "v": 1,
      "m": 1
     },
     {
      "x": 5,
      "v": 1,
      "m": 1
     },
     {
      "x": 18,
      "v": 1,
      "m": 1
     },
     {
      "x": 20,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Spriggan Sap",
    "v": "15",
    "w": "0.2",
    "r": "Cannot be harvested or collected; best source is merchants.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 2,
      "v": 1,
      "m": 1
     },
     {
      "x": 7,
      "v": 1,
      "m": 1
     },
     {
      "x": 13,
      "v": 1,
      "m": 1
     },
     {
      "x": 24,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Swamp Fungal Pod",
    "v": "5",
    "w": "0.25",
    "r": "Harvested from Swamp Fungal Pod, common in the tundra marsh of Hjaalmarch.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 31,
      "v": 1,
      "m": 1
     },
     {
      "x": 33,
      "v": 1,
      "m": 1
     },
     {
      "x": 44,
      "v": 1,
      "m": 1
     },
     {
      "x": 45,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Taproot",
    "v": "15",
    "w": "0.5",
    "r": "Collected from dead Spriggans.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 16,
      "v": 1,
      "m": 1
     },
     {
      "x": 38,
      "v": 1,
      "m": 1
     },
     {
      "x": 46,
      "v": 1,
      "m": 1
     },
     {
      "x": 52,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Thistle Branch",
    "v": "1",
    "w": "0.1",
    "r": "Harvested from Thistle.",
    "o": "BS",
    "q": "Common",
    "e": [
     {
      "x": 15,
      "v": 1,
      "m": 1
     },
     {
      "x": 36,
      "v": 1,
      "m": 1
     },
     {
      "x": 41,
      "v": 1,
      "m": 1
     },
     {
      "x": 43,
      "v": 1,
      "m": "0.75"
     }
    ]
   },
   {
    "n": "Torchbug Thorax",
    "v": "1",
    "w": "0.1",
    "r": "Collected by catching Torchbugs. Found below the snowline after dark.",
    "o": "BS",
    "q": "None (Common)",
    "e": [
     {
      "x": 26,
      "v": 1,
      "m": 1
     },
     {
      "x": 31,
      "v": 1,
      "m": 1
     },
     {
      "x": 47,
      "v": 1,
      "m": 1
     },
     {
      "x": 52,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Trama Root",
    "v": "1",
    "w": "0.2",
    "r": "Harvested from trama root plants.",
    "o": "DB",
    "q": "",
    "e": [
     {
      "x": 3,
      "v": 1,
      "m": 1
     },
     {
      "x": 10,
      "v": 1,
      "m": 1
     },
     {
      "x": 48,
      "v": 1,
      "m": 1
     },
     {
      "x": 54,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Troll Fat",
    "v": "15",
    "w": "1",
    "r": "Collected from dead Trolls.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 1,
      "v": 1,
      "m": 1
     },
     {
      "x": 27,
      "v": 1,
      "m": 1
     },
     {
      "x": 28,
      "v": 1,
      "m": 1
     },
     {
      "x": 43,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Tundra Cotton",
    "v": "1",
    "w": "0.1",
    "r": "Harvested from Tundra Cotton, found in Whiterun Hold.",
    "o": "BS",
    "q": "Common",
    "e": [
     {
      "x": 8,
      "v": 1,
      "m": 1
     },
     {
      "x": 9,
      "v": 1,
      "m": 1
     },
     {
      "x": 19,
      "v": 1,
      "m": 1
     },
     {
      "x": 42,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Vampire Dust",
    "v": "25",
    "w": "0.2",
    "r": "Collected from dead Vampires.",
    "o": "BS",
    "q": "Rare",
    "e": [
     {
      "x": 0,
      "v": 1,
      "m": 1
     },
     {
      "x": 29,
      "v": 1,
      "m": 1
     },
     {
      "x": 37,
      "v": 1,
      "m": 1
     },
     {
      "x": 46,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Void Salts",
    "v": "125",
    "w": "0.2",
    "r": "Collected from dead Storm Atronachs.",
    "o": "BS",
    "q": "Rare",
    "e": [
     {
      "x": 1,
      "v": 1,
      "m": 1
     },
     {
      "x": 19,
      "v": 1,
      "m": 1
     },
     {
      "x": 42,
      "v": 1,
      "m": 1
     },
     {
      "x": 54,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Wheat",
    "v": "5",
    "w": "0.1",
    "r": "Food. Harvested from wheat bushels, found in various farms.",
    "o": "BS",
    "q": "Common",
    "e": [
     {
      "x": 4,
      "v": 1,
      "m": 1
     },
     {
      "x": 14,
      "v": 1,
      "m": 1
     },
     {
      "x": 31,
      "v": 1,
      "m": 1
     },
     {
      "x": 45,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "White Cap",
    "v": "0",
    "w": "0.3",
    "r": "Harvested from White Cap mushrooms, found in various caves.",
    "o": "BS",
    "q": "Uncommon",
    "e": [
     {
      "x": 15,
      "v": 1,
      "m": 1
     },
     {
      "x": 35,
      "v": 1,
      "m": 1
     },
     {
      "x": 46,
      "v": 1,
      "m": 1
     },
     {
      "x": 51,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Wisp Wrappings",
    "v": "2",
    "w": "0.1",
    "r": "Collected from dead Wispmothers.",
    "o": "BS",
    "q": "None (Uncommon)",
    "e": [
     {
      "x": 10,
      "v": 1,
      "m": 1
     },
     {
      "x": 12,
      "v": 1,
      "m": 1
     },
     {
      "x": 42,
      "v": 1,
      "m": 1
     },
     {
      "x": 47,
      "v": 1,
      "m": 1
     }
    ]
   },
   {
    "n": "Yellow Mountain Flower",
    "v": "2",
    "w": "0.1",
    "r": "Harvested from the yellow variety of Mountain Flower.",
    "o": "DG",
    "q": "None",
    "e": [
     {
      "x": 4,
      "v": 1,
      "m": 1
     },
     {
      "x": 14,
      "v": 1,
      "m": 1
     },
     {
      "x": 23,
      "v": 1,
      "m": "1.25"
     },
     {
      "x": 43,
      "v": 1,
      "m": 1
     }
    ]
   }
  ],
  "p": [
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   []
  ],
  "s": [
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false
  ]
 },
 "e": {
  "h": {
   "Cure Disease": 0,
   "Damage Health": 1,
   "Damage Magicka Regen": 2,
   "Damage Magicka": 3,
   "Damage Stamina Regen": 4,
   "Damage Stamina": 5,
   "Fear": 6,
   "Fortify Alteration": 7,
   "Fortify Barter": 8,
   "Fortify Block": 9,
   "Fortify Carry Weight": 10,
   "Fortify Conjuration": 11,
   "Fortify Destruction": 12,
   "Fortify Enchanting": 13,
   "Fortify Health": 14,
   "Fortify Heavy Armor": 15,
   "Fortify Illusion": 16,
   "Fortify Light Armor": 17,
   "Fortify Lockpicking": 18,
   "Fortify Magicka": 19,
   "Fortify Marksman": 20,
   "Fortify One-handed": 21,
   "Fortify Pickpocket": 22,
   "Fortify Restoration": 23,
   "Fortify Smithing": 24,
   "Fortify Sneak": 25,
   "Fortify Stamina": 26,
   "Fortify Two-handed": 27,
   "Frenzy": 28,
   "Invisibility": 29,
   "Lingering Damage Health": 30,
   "Lingering Damage Magicka": 31,
   "Lingering Damage Stamina": 32,
   "Paralysis": 33,
   "Ravage Health": 34,
   "Ravage Magicka": 35,
   "Ravage Stamina": 36,
   "Regenerate Health": 37,
   "Regenerate Magicka": 38,
   "Regenerate Stamina": 39,
   "Resist Fire": 40,
   "Resist Frost": 41,
   "Resist Magic": 42,
   "Resist Poison": 43,
   "Resist Shock": 44,
   "Restore Health": 45,
   "Restore Magicka": 46,
   "Restore Stamina": 47,
   "Slow": 48,
   "Waterbreathing": 49,
   "Weakness to Fire": 50,
   "Weakness to Frost": 51,
   "Weakness to Magic": 52,
   "Weakness to Poison": 53,
   "Weakness to Shock": 54
  },
  "z": 55,
  "a": [
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true,
   true
  ],
  "b": [
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false
  ],
  "d": [
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null
  ],
  "l": [
   {
    "n": "Cure Disease",
    "f": true,
    "x": 0
   },
   {
    "n": "Damage Health",
    "f": false,
    "x": 1
   },
   {
    "n": "Damage Magicka Regen",
    "f": false,
    "x": 2
   },
   {
    "n": "Damage Magicka",
    "f": false,
    "x": 3
   },
   {
    "n": "Damage Stamina Regen",
    "f": false,
    "x": 4
   },
   {
    "n": "Damage Stamina",
    "f": false,
    "x": 5
   },
   {
    "n": "Fear",
    "f": false,
    "x": 6
   },
   {
    "n": "Fortify Alteration",
    "f": true,
    "x": 7
   },
   {
    "n": "Fortify Barter",
    "f": true,
    "x": 8
   },
   {
    "n": "Fortify Block",
    "f": true,
    "x": 9
   },
   {
    "n": "Fortify Carry Weight",
    "f": true,
    "x": 10
   },
   {
    "n": "Fortify Conjuration",
    "f": true,
    "x": 11
   },
   {
    "n": "Fortify Destruction",
    "f": true,
    "x": 12
   },
   {
    "n": "Fortify Enchanting",
    "f": true,
    "x": 13
   },
   {
    "n": "Fortify Health",
    "f": true,
    "x": 14
   },
   {
    "n": "Fortify Heavy Armor",
    "f": true,
    "x": 15
   },
   {
    "n": "Fortify Illusion",
    "f": true,
    "x": 16
   },
   {
    "n": "Fortify Light Armor",
    "f": true,
    "x": 17
   },
   {
    "n": "Fortify Lockpicking",
    "f": true,
    "x": 18
   },
   {
    "n": "Fortify Magicka",
    "f": true,
    "x": 19
   },
   {
    "n": "Fortify Marksman",
    "f": true,
    "x": 20
   },
   {
    "n": "Fortify One-handed",
    "f": true,
    "x": 21
   },
   {
    "n": "Fortify Pickpocket",
    "f": true,
    "x": 22
   },
   {
    "n": "Fortify Restoration",
    "f": true,
    "x": 23
   },
   {
    "n": "Fortify Smithing",
    "f": true,
    "x": 24
   },
   {
    "n": "Fortify Sneak",
    "f": true,
    "x": 25
   },
   {
    "n": "Fortify Stamina",
    "f": true,
    "x": 26
   },
   {
    "n": "Fortify Two-handed",
    "f": true,
    "x": 27
   },
   {
    "n": "Frenzy",
    "f": false,
    "x": 28
   },
   {
    "n": "Invisibility",
    "f": true,
    "x": 29
   },
   {
    "n": "Lingering Damage Health",
    "f": false,
    "x": 30
   },
   {
    "n": "Lingering Damage Magicka",
    "f": false,
    "x": 31
   },
   {
    "n": "Lingering Damage Stamina",
    "f": false,
    "x": 32
   },
   {
    "n": "Paralysis",
    "f": false,
    "x": 33
   },
   {
    "n": "Ravage Health",
    "f": false,
    "x": 34
   },
   {
    "n": "Ravage Magicka",
    "f": false,
    "x": 35
   },
   {
    "n": "Ravage Stamina",
    "f": false,
    "x": 36
   },
   {
    "n": "Regenerate Health",
    "f": true,
    "x": 37
   },
   {
    "n": "Regenerate Magicka",
    "f": true,
    "x": 38
   },
   {
    "n": "Regenerate Stamina",
    "f": true,
    "x": 39
   },
   {
    "n": "Resist Fire",
    "f": true,
    "x": 40
   },
   {
    "n": "Resist Frost",
    "f": true,
    "x": 41
   },
   {
    "n": "Resist Magic",
    "f": true,
    "x": 42
   },
   {
    "n": "Resist Poison",
    "f": true,
    "x": 43
   },
   {
    "n": "Resist Shock",
    "f": true,
    "x": 44
   },
   {
    "n": "Restore Health",
    "f": true,
    "x": 45
   },
   {
    "n": "Restore Magicka",
    "f": true,
    "x": 46
   },
   {
    "n": "Restore Stamina",
    "f": true,
    "x": 47
   },
   {
    "n": "Slow",
    "f": false,
    "x": 48
   },
   {
    "n": "Waterbreathing",
    "f": true,
    "x": 49
   },
   {
    "n": "Weakness to Fire",
    "f": false,
    "x": 50
   },
   {
    "n": "Weakness to Frost",
    "f": false,
    "x": 51
   },
   {
    "n": "Weakness to Magic",
    "f": false,
    "x": 52
   },
   {
    "n": "Weakness to Poison",
    "f": false,
    "x": 53
   },
   {
    "n": "Weakness to Shock",
    "f": false,
    "x": 54
   }
  ],
  "p": [
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   [],
   []
  ],
  "s": [
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false,
   false
  ]
 },
 "m": {
  "o": {
   "BS": 95,
   "DB": 11,
   "DG": 5,
   "HF": 2
  }
 }
};
}( window.spot_ns = window.spot_ns || {}, jQuery ));
