(function( spot_ns, $, undefined ) {
  "use strict";

	spot_ns.check_sum = spot_ns.check_sum || {};

	var hashCode = function( big ) {
		var hash = 0, i, chr, len;
		if( big.length === 0 ) return hash;
		for( i = 0, len = big.length; i < len; i++ ) {
			chr   = big.charCodeAt(i);
			hash  = ((hash << 5) - hash) + chr;
			hash |= 0; // Convert to 32bit integer
		}
		return hash;
	};

	var hashify = function( big ) {
		var a = ( hashCode( big ) & 0xFFFFFF ).toString( 16 ).toUpperCase();
		var b = "000000" + a;
		var c = b.substr( -6 );
		return( c.substr( 0, 3 ) + "-" + c.substr( 3, 3 ) );
	};

	spot_ns.JSON_dump = function( cs_tag, myj ) {
		var space = cs_tag===""?null:' ';
		var myJSON = JSON.stringify( myj, null, space );
		spot_ns.check_sum[ cs_tag ] = hashify( myJSON );

    $("#fullJSON").text(
				"// autogenerated content -- DO NOT MODIFY\n"
			+ "(function( spot_ns, \$, undefined ) {\n\n"
			+ "spot_ns.check_sum = " + JSON.stringify( spot_ns.check_sum, null, space ) + ";\n\n"
			+ "spot_ns.index = \n"
			+ myJSON
			+ ";\n}( window.spot_ns = window.spot_ns || {}, jQuery ));\n"
		);
	}

}( window.spot_ns = window.spot_ns || {}, jQuery ));

// vim:set tabstop=2 shiftwidth=2 noexpandtab:
